### ISSUE TITLE
new transport zone

### ISSUE THREAD

**Issue by g0ldingkev** [vmware/powernsx#103]
creating a new transport zone is throwing an error, as below..  any ideas where i'm going wrong?

New-NsxTransportZone : Cannot process argument transformation on parameter 'Cluster'. Cannot convert the "PBOLABDELL" value of
type "System.String" to type "VMware.VimAutomation.ViCore.Interop.V1.Inventory.ClusterInterop[]".
At line:1 char:42
+ New-NsxTransportZone -name test -Cluster PBOLABDELL -ControlPlaneMode UNICAST_MO ...
+                                          ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-NsxTransportZone], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,New-NsxTransportZone

**Comment by nmbradford** [comment]
The command is telling you it is expecting a collection (the [] at the end of the type name means 1 or more objects) type of VMware.VimAutomation.ViCore.Interop.V1.Inventory.ClusterInterop  - which is what is returned by the PowerCLI Get-Cluster command.

So, something like the following would work:

```
$cluster = Get-Cluster PBOLABDELL
New-NsxTransportZone -name test -Cluster $cluster -ControlPlaneMode UNICAST_MODE
```
or the same thing in one line:
```
New-NsxTransportZone -name test -Cluster (Get-Cluster PBOLABDELL) -ControlPlaneMode UNICAST_MODE
```
Finally - in case you want more than one cluster...
```
$cluster1 = Get-Cluster PBOLABDELL
$cluster2 = Get-Cluster MYOTHERCLUSTER
New-NsxTransportZone -name test -Cluster $cluster1,$cluster2 -ControlPlaneMode UNICAST_MODE
```

**Comment by g0ldingkev** [comment]
yeah that makes sense, tried providing a string and a string from a variable..  

thanks

**Comment by nmbradford** [comment]
No problem :)

**Comment by forbsy** [comment]
One other question. I have Visio Pro for Office 365 installed. When I run the .\NsxObjectDiagram.ps1 it launches Visio, but then errors. Just wondering if the version of Visio I'm using is the issue?
![visiotool-1](https://cloud.githubusercontent.com/assets/25696139/22848484/df4b6386-efc2-11e6-98fd-2ba8331fef3c.PNG)
