### ISSUE TITLE
SG: Dynamic Inclusion

### ISSUE THREAD

**Issue by smarunich** [vmware/powernsx#116]
SG: Dynamic Inclusion 
Single section, to define security group using dynamic inclusion based on multiple security tags using AND logic. 

Example, security group SG-PROD-WEB-APP1 - to join SG - VM needs to have 3 Security Tags  (PROD, WEB, APP1) to enter SG 

THANK YOU
Sergey & Dev

**Comment by nmbradford** [comment]
pushing to 2.2 as non critical feature request - first cab of the rank for 2.2 though guys, sorry for the delay!

**Comment by dcoghlan** [comment]
This functionality is now available. Fixed by #378
