### ISSUE TITLE
NSX Visio Diagram Tool

### ISSUE THREAD

**Issue by forbsy** [vmware/powernsx#125]
Hi. I'm trying to run the .\NsxObjectCapture.ps1 script but getting many errors. I'm a newbie to PowerCLI so not sure if I'm doing something incorrect? I've already connected to NSX manager and vCenter successfully. Attached is a screenshot.
![visiotool](https://cloud.githubusercontent.com/assets/25696139/22844807/e7c6bfb6-efad-11e6-8e59-8c331d69ee9a.PNG)

**Comment by nmbradford** [comment]
Looks a lot like there's an issue with how you downloaded it given that there is HTML in the error output above.  Suggest you either clone the git repo (requires git for windows) or just download the zip (Clone or Download button on the main page of the git repo on GH).  You may need to 'unblock' the zip file depending on version and config of Windows you use if you choose the zip method.

**Comment by forbsy** [comment]
Thanks! I cloned the zip and it worked like a charm. Very cool.
Cheers

**Comment by nmbradford** [comment]
Welcome - happy days!
