### ISSUE TITLE
NSX Visio Drawing Tool

### ISSUE THREAD

**Issue by forbsy** [vmware/powernsx#126]
With respect to the NSX Visio Drawing Tool. 
I have Visio Pro for Office 365 installed. When I run the .\NsxObjectDiagram.ps1 it launches Visio, but then errors. Just wondering if the version of Visio I'm using is the issue?
![visiotool-1](https://cloud.githubusercontent.com/assets/25696139/22858012/13271606-f080-11e6-9717-0c8d16c7fd03.PNG)

**Comment by nmbradford** [comment]
The same error occurs if you run the tool with a trial copy of Visio - you must have a licensed copy installed.  Is that the case here, or do you have a licensed and activated Office 365 Visio install that is giving you this error?

**Comment by forbsy** [comment]
It's licensed via my work Office365 subscription.
![visiotool-2](https://cloud.githubusercontent.com/assets/25696139/22869775/811b98ea-f16f-11e6-8e96-c80ba780dbd1.PNG)

**Comment by nmbradford** [comment]
Thats a pity - looks as if the Visio API is blocked in 365 activated product?  I don't have an equivalent to test with unfortunately.  Any chance you could raise a ticket with your 365 provider to see if this is a known issue and if there is any work around?  Its literally a 'should the Visio API be accessible to me as a subscribed user.'

**Comment by forbsy** [comment]
Sure thing. Thanks for responding.

**Comment by nmbradford** [comment]
no problem, thanks for pursuing it!

**Comment by nmbradford** [comment]
Confirmed, trial or 365 activated version of visio do not have API enabled. :(
