### ISSUE TITLE
Launch PowerNSX Script with Windows Scheduled Task

### ISSUE THREAD

**Issue by tomErne** [vmware/powernsx#142]
Hello

First of all, you did a great job! PowerNSX is great...

We would like to start a .ps1 script with Windows 2012 Task Scheduler. We receive the following error:

> WARNING: PowerNSX requires PowerCLI. Assembly VMware.VimAutomation.Vds.Commands not found.  Some required PowerCli types are not available in this PowerShell session.  Please ensure you are running PowerNSX in a PowerCLI session, or have manually loaded the required assemblies.

In the first line of the script we are loading PowerCli and then the PowerNSX module:
```
Add-PSSnapin VMware.VimAutomation.Core -WarningAction SilentlyContinue
Import-Module -Name "\\xxxx\tools$\PowerShellModules\PowerNSX"
```

When we start the script directly in the PowerCli console everthing works fine.

Does anyone have an idea or tipp?

Kind Regards
Tom

**Comment by nmbradford** [comment]
Hi Tom - the master branch of PowerNSX only supports PowerCLI 6 an above (and all support for 5.5 will go away in the 2.1 release).  The main reason for this is the change in PowerCLI to support module based packaging, not snapin based.  To fix, upgrade to PowerCLI 6+ and use import-module to import the powercli modules (though this isnt mandatory, if you are using PoSH 4+, the module loading should be automatic, so you dont need to explicitly load either PowerCLI or PowerNSX modules.)
