### ISSUE TITLE
install script does not detect a correctly installed powercli

### ISSUE THREAD

**Issue by jslabonte** [vmware/powernsx#147]
The function "check-powercli" which poll the registry for an uninstall key belonging to "powercli" return that it did not find a valid install of powercli.

VMware PowerCLI 6.5 Release 1 build 4624819 is installed on Windows 10 with French language pack.
That line seem to be the problem:
       ` $PowerCli = get-childitem "HKLM:Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall" | % { $_ | get-itemproperty | ? { $_.displayName -match 'PowerCLI' }}`

I have powercli installed, but no such registry key.

Thanks!

**Comment by nmbradford** [comment]
Thanks @jslabonte - Ill look to address in 2.1.  Are you saying the Uninstall key doesn't exist on French lang pack, or that the display name for PowerCLI is localised?

**Comment by jslabonte** [comment]
@mmbradford -
I'm not sure as the windows registry fall outside of my comfort zone, but I can tell you that the key for powercli is:

` "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{2E4FAF13-B720-4385-A23C-5C38D742D6C6}"`

You will find the export attached in case it could be usefull.

**Comment by jslabonte** [comment]
Well, "DisplayName" is properly set it seem, I will try to diagnose this further.

**Comment by nmbradford** [comment]
Will be moving detection routines to import-module --listavailable in 2.2 timeframe, deferring as will be fixed in #239

**Comment by dcoghlan** [comment]
Fixed as part of #239
