### ISSUE TITLE
Move PowerCLI/.NET Assembly check inside of Connect-NsxServer

### ISSUE THREAD

**Issue by vScripter** [vmware/powernsx#15]
Requesting some discussion around potentially moving the actual calling of `Check-PowerCLIAssemblies` from the module root in to the `Connect-NsxServer` function.

A couple things that come to mind:
- I started building out Pester tests and pester chokes when PowerCLI, or any of the required .NET assemblies, are not loaded prior to running tests, since the module needs to be loaded into the pester scope. 
- It's not possible to just load the module and browse the functions, read help, etc., without loading PowerCLI and/or the required assemblies.

It may make it easier to offload this check into `Connect-NsxServer` since that function needs to be ran, anyway.

**Comment by nmbradford** [comment]
Kudos for starting to tackle the Pester challenge - the lack of proper tests has been bugging me for a while, awesome to see someone thinking about it.  I'm also in a few different minds about the assembly check, where it should exist (if at all) etc.  Ill give it some thought and come back on this.

**Comment by vScripter** [comment]
Sounds good; I also thought this afternoon after I submitted the issue; what about instead of a hard check on module load, we at least throw a warning with detail about what exactly needs to be loaded, and then maybe a hard check when running `Connect-NsxServer`. 

Generally speaking, I'm always torn on how much consideration to include as far as supporting these types of validation checks; to that point, I can appreciate the pondering you talk about.

**Comment by nmbradford** [comment]
@vScripter I had a think about this and agree with you that we need to be able to load PowerNSX without requiring running in a PowerCLI window.  I previously wasnt using the autoloaded module functionality of the manifest file as I was still wanting to support PowerCLI 5 (snapin based) users, but thats now a fair way in the past, so Ive made the following changes:

**Comment by vScripter** [comment]
Tested and working! Change looks good; can't see any issues that would arise handling it this way. :shipit:
