### ISSUE TITLE
Fix Unapproved Verbs

### ISSUE THREAD

**Issue by vScripter** [vmware/powernsx#16]
Rename the following functions to use approved verbs.
- `Where-NsxVmUsed`
- `Redeploy-NsxEdge`

Proposed change ideas:
- **Instead of `Where-NsxVmUsed`**
    - `Get-NsxVmSecurityPosture` - return similar results as current command
    - `Get-NsxVmFirewallRule` - break out results for L3 & L2 firewall rules and only return those for this command
    - `Get-NsxVmSecurityGroup` - break out results for Security Groups and only return those results for this command
- **Instead of `Redeploy-NsxEdge`**
    - `Invoke-NsxEdgeRedeploy` - Same functionality as current function
    - `New-NsxEdge -Redeploy` - move the functionality into the `New-NsxEdge` function via the addition of a `-Redeploy` parameter

**Comment by nmbradford** [comment]
It seems great minds think alike ;)  I fixed these just yesterday (commit 6f1d7e2545bb7034dd91ab3d6e7bd958afe3a2b3).  I did go a slightly different direction to you, but agree that the change was needed to align with standard verb BP.  Happy to discuss if you think the changes were in the wrong direction.

**Comment by vScripter** [comment]
Ha! Outstanding; I have no issues/suggestions to better what you did; I'll close this out.
