### ISSUE TITLE
Add-NsxIpSetMember handle adding multiple addresses, even if one already exists.

### ISSUE THREAD

**Issue by dcoghlan** [vmware/powernsx#178]
when specifying multiple IP entries to add to an IP Set, if one of the given entries already exists in the IP Set, the cmdlet throws and error and stops.

Look at the correct method to handle such a situation so that the other entries that don't already exist in the IP Set specified are still added.

Setting -ErrorAction SilentlyContinue should not be used as it then allows duplicate entries to be added to the IP Set which is what the cmdlet is trying to protect against.

Command
```
Get-NsxIpSet -scopeid universalroot-0 UIS4_NSX_ZV_TEST | Add-NsxIpSetMember -IPAddress 10.1.1.1,10.66.234.43,1.5.5.5
```

Error
```
Value 10.1.1.1 is already a member of the IPSet UIS4_NSX_ZV_TEST
At /git/Github/dcoghlan_powernsx/PowerNSX.psm1:20966 char:21
+ ...             throw "Value $value is already a member of the IPSet $($i ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Value 10.1.1.1 ...UIS4_NSX_ZV_TEST:String) [], RuntimeException
    + FullyQualifiedErrorId : Value 10.1.1.1 is already a member of the IPSet UIS4_NSX_ZV_TEST
```

**Comment by nmbradford** [comment]
Understood - do you want a switch to allow user to continue on duplicate with just a warning that the duplicate address wont be added?

**Comment by dcoghlan** [comment]
I think just a warning would be sufficient

**Comment by nmbradford** [comment]
so default behaviour will be to not add the duplicate, but throw a warning and continue?
