### ISSUE TITLE
New-NsxFirewallRule does not accept CIDR addressing as source/destination

### ISSUE THREAD

**Issue by dcoghlan** [vmware/powernsx#180]
New-NsxFirewallRule currently only accepts an object as the source/destination.

Functionality is required so that it is able to create firewall rules where the source or destination can contain:

Only CIDR addresses
Only objects (VM, LS, SG, Cluster etc)
Combination of both of the above.

**Comment by nmbradford** [comment]
I was sure Id already done this, but the code doesnt lie :(.  How urgent Dale?  Can work on it today if necessary?

**Comment by dcoghlan** [comment]
ip host as source/destination of firewall rule is covered in #184 
ip range/network as source/destination of firewall rule is covered in pull request #188

**Comment by dcoghlan** [comment]
closed via #184 & #188
