### ISSUE TITLE
Three Tier App wiki page has references to BitBucket links.

### ISSUE THREAD

**Issue by nmbradford** [vmware/powernsx#19]
Burkey - can you update with GH hosted links?

**Comment by pandom** [comment]
This is redundant as powernsx.github.io will replace the wiki.

**Comment by nmbradford** [comment]
are they fixed there?

**Comment by pandom** [comment]
Yes, I have removed it. I need to host a new 3TA diagram somewhere at a
later stage.

Regards,

Anthony Burke
w: networkinferno.net
t: @pandom_  <http://www.twitter.com/pandom_>
s: pandom.
icq: 672820731

**Comment by nmbradford** [comment]
can host on your gh pages repo yes?

**Comment by nmbradford** [comment]
Moving to 2.2 as non critical

**Comment by pandom** [comment]
Reviewing this. This has been fixed a while back in transition to Github.io
