### ISSUE TITLE
Update Nsx-IPSet

### ISSUE THREAD

**Issue by hootdogg** [vmware/powernsx#207]
Hello,

Great job on PowerNSX! It is very helpful for me so far.
I have a question, is there a way to update the values of an existing IPset using PowerNSX?
I would like to update the IPaddresses value if possible without creating a new IPSet.

Thank you

Sean

**Comment by dcoghlan** [comment]
Hi Sean

The master branch has been updated with the following cmdlets which allow IPSet manipulation and should provide what your after.

Add-NsxIpSetMember
Remove-NsxIpSetMember

Dale

**Comment by hootdogg** [comment]
Dale,

Thank you very much, this works perfectly!  I was able to use the Add-NsxIpSetMember cmdlet in my scripts and all is working well.

Sean

**Comment by dcoghlan** [comment]
No worries Sean, Glad to help.
