### ISSUE TITLE
Unable to Change/Add/Delete Firewall Rules on NSX Edge (not DFW Rules)

### ISSUE THREAD

**Issue by hchchchc2** [vmware/powernsx#228]
hi,
PowerNSX is such a cool stuff !
i tried to find a cmdlet that helps me to change, add and delete firewall rules on a NSX Edge (not the Distributed FW Rules).
is there a way with PowerNSX ?
thanks in advance, chris

**Comment by nmbradford** [comment]
Hi Chris, not currently, but this is a recurring request from multiple sources recently and Ill be looking to prioritise some work on it asap.

**Comment by nmbradford** [comment]
closing and referencing earlier raised duplicate issue #70
