### ISSUE TITLE
Could not add firewall rule to the edge router 

### ISSUE THREAD

**Issue by vanibs** [vmware/powernsx#230]
There is not direct PowerCLI to add firewall rule to the Edge router.
I tried the following way(since there is not direct command) and that did not work either.
By using the following method, I could able to change the Default policy action and able to edit the existing Firewall rule, but not able to add a new firewall rule to the edge. 
 
$TsEdge1 = get-nsxedge $TsEdge
$TsEdge1.features.firewall.defaultPolicy.action = "accept"
$TsEdge1 | Set-NsxEdge -confirm:$false | out-null

**Comment by nmbradford** [comment]
Seems to be a hot topic lately!  Closing this due to duplicate issue - please subscribe to the linked issue as that is where I will update on progress.. Issue #228

**Comment by nmbradford** [comment]
ref duplicate #70
