### ISSUE TITLE
DFW Timers fail on Pester test suite

### ISSUE THREAD

**Issue by pandom** [vmware/powernsx#237]
DFW Timers causes DFW pester tests to fail on different platforms.

Check code or tests.

**Comment by nmbradford** [comment]
fix for 2.1 as its breaking the test suite currently

**Comment by pandom** [comment]
More details required here please @nmbradford - They pass on core for macOS/Linux.

Do they fail on Windows?

**Comment by nmbradford** [comment]
yup - that would be the 'different platforms'.  Check different versions of NSX as well.  I'm currently testing on 6.2.2, 6.2.7 and 6.3.1
