### ISSUE TITLE
PowerNSX to Powershell Gallery

### ISSUE THREAD

**Issue by pandom** [vmware/powernsx#239]
Prepare PowerNSX for use in PowerShell Gallery.

This will ensure PowerCLI and PowerNSX can be installed from PowerShell Gallery if desired.

**Comment by alagoutte** [comment]
Can be close ? Now it is available https://www.powershellgallery.com/packages/PowerNSX

**Comment by nmbradford** [comment]
resolved as of release of version 3.  See updated installation wiki for details.  https://powernsx.github.io/windowsinstall/
