### ISSUE TITLE
Update installation documentation for Core

### ISSUE THREAD

**Issue by nmbradford** [vmware/powernsx#267]
Update to alpha 18 recommended, and specifically indicate issues exist with Beta1 that prevent its use.

**Comment by pandom** [comment]
Completed.

> The PowerNSX team recommend PowerShell core 6.0.0-alpha18 for use with PowerNSX on macOS. There is a Powershell bug in 6.0.0-beta1 that breaks functionality for macOS. It can be downloaded [here](https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-alpha.18)


https://github.com/powernsx/powernsx.github.io/commit/f5c04ce552e9dc598df662c926bea9c2d94dd9ec

**Comment by nmbradford** [comment]
For completeness, the same requirement exists for Linux PowerShell Core.

**Comment by pandom** [comment]
Updated for completeness.

Updated to include Linux on this merge. https://github.com/powernsx/powernsx.github.io/commit/2b11b040f6393ae5d6b35fa73d011a36bdb13e4d
