### ISSUE TITLE
Get-NsxSecurityTagAssignment throwing errors on Template objects

### ISSUE THREAD

**Issue by kanecharles92** [vmware/powernsx#279]
As discussed with Anthony, the cmdlet `Get-NsxSecurityTagAssignment` will throw errors when looping through the result set when it gets to a VM object that is a template.

See the below image for an example.

![image](https://cloud.githubusercontent.com/assets/5733336/26617934/3e0b4072-461b-11e7-84cd-0d2c49f28ed7.png)

`vm-19959` correlates with `2017-2-25 Red Hat 7.x` template in our situation according to the mob.

I suspect this might also be the case for anywhere else that you are looping through tag result sets from the API, as I am now aware (thanks to Anthony) you are unable to specify a filter; the API will return a full set and you do the searching within PowerNSX.

**Comment by kanecharles92** [comment]
As a follow up comment, until the API is fixed, would it be possible to somehow set the result set that is returned for all vms/all tags so that it can be searched using other Powershell means?

In this particular example, I was finding all lnx* and win* VMs that had the ST-DFW-Exclusion tag, and then attempting to get a list of all other tags assigned to those VMs. It was too inefficient to run the `Get-NsxSecurityTagAssignment` cmdlet for every VM in the returned list as it will pull a fresh entire list from NSX each time it runs.

**Comment by pandom** [comment]
As discussed there are enhancements in 6.3 API to improve the ability to scope tag based operations.

The cmdlet does not utilize these enhancements. See #280 for details
