### ISSUE TITLE
Enhancement - Detection of PowerCLI installation through Powershell Gallery

### ISSUE THREAD

**Issue by malfunctioningeddie** [vmware/powernsx#287]
I just went through and installed Powershell 6.5.1 through the Install-Module function that is referenced on the VMware {code} website and tried to tdo the PowerNSX install but it doesn't detect the modules in the Powershell modules directory. 

The current workaround is to just throw the PowerNSX modules into that directory and not do the automated install but I figured I would raise this as a feature request or enhancement.

**Comment by alagoutte** [comment]
Hi,

You need to use master branch.. :-D

**Comment by pandom** [comment]
Hi,

The issue has been raised and referenced here in #206 

Will be fixed in #239 . Comments have the workaround. Use the master branch for now. 

Thanks for raising.

**Comment by nmbradford** [comment]
Resolved with version 3.  See updated installation wiki for details. https://powernsx.github.io/windowsinstall/
