### ISSUE TITLE
Set-NSXEdge only support "Edge services gateway". It doesn't support DLR.

### ISSUE THREAD

**Issue by yktsubo** [vmware/powernsx#291]
Hi 
The function doesn't support DLR configuration change by "Set-NSXEdge".
According to NSX API Guide, we can change DLR config with the same way as ESG is using.
Therefore, in my opinion,  we may support DLR configuration change by the function.
Or do you think we had better create another function (named Set-NSXLogicalRouter) to change DLR config?
Could you give me your opinion?

No matter which way we may adopt, I will write code for it.

**Comment by pandom** [comment]
Set-NsxLogicalRouter would be the approach at a guess.

New-NsxLogicalRouterInterface/InterfaceSpec have set precedence there.

**Comment by yktsubo** [comment]
Thanks for your comment.
Let me confirm why it's better that we will introduce new command because this is regarding the powernsx policy.
Looking at the powernsx code, I thought that powernsx is developped for users to easily use NSX.
So powernsx doesn't adopt the same design as NSX original API even though same REST request  is used.
Because of above, introducing new command is better.Is it corret?

**Comment by pandom** [comment]
Yes.

That's a great reasoning. It also clearly highlights edges vs DLRs. Whilst they are the same from an API call we can filter the response to only return logical routers with get-nsxlogicalrouter vs get-nsxedge.

The NSX API design has a lot to be desired. PowerNSX allows us to honor what we need to and enhance others.

Happy for Overlord Bradford to chime in here.

**Comment by nmbradford** [comment]
yeah - the need for set-nsxlogicalrouter is hinted at by @koh39 in #196.  @yktsubo, while my general approach is to keep language and experience as close to the UI as possible, int he case of edge vs DLR, and the subtle and not so subtle differences between their respective APIs, i chose to separate all the functionality and pipeline behaviour for them both, so there will always be separate cmdlets, even when the functions are very similar.  In this case, yes, we need a separate set-nsxlogicalrouter cmdlet.  Feel free to create a PR - appreciate the input.

**Comment by yktsubo** [comment]
Thank you so much for comments.
I understood the concept of powernsx.
I will let you know when the code is ready.

**Comment by yktsubo** [comment]
As #300 is merged, let this be closed.
