### ISSUE TITLE
Update Controller State cmdlet required

### ISSUE THREAD

**Issue by dcoghlan** [vmware/powernsx#299]
Need the ability to run the "Update Controller State" function that is available in the UI.

**Comment by dcoghlan** [comment]
The API to achieve this is ```PUT /api/2.0/vdn/controller/synchronize```

**Comment by alagoutte** [comment]
>The API to achieve this is PUT /api/2.0/vdn/controller/synchronize

There is no reference on this URL on nsx_63_api.pdf (coming from another doc ?!)
