### ISSUE TITLE
Enhancement: Alias British English functions 

### ISSUE THREAD

**Issue by malfunctioningeddie** [vmware/powernsx#323]
As of right now on all NSX dynamic routing functions are defined as Neighbour 
` Get-NSXEdge | Get-NSXEdgeRouting | New-NSXEdgeBgp**Neighbour**` 

Where as I am used to the spelling and keep getting the following:

`New-NSXEdgeBGPNeighbor : The term 'New-NSXEdgeBGPNeighbor' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

In the future is it possible to alias the routing protocol definition functions with the American English version as well?  I can work on this when I get some spare time and issue a pull request if that works for you.

**Comment by nmbradford** [comment]
actually - that should be 'Alias the rest of the world English' ;). 

Id recommend a separate alias definition outside PowerNSX in your PowerShell profile as a better approach.

**Comment by malfunctioningeddie** [comment]
I mean after realizing what was happening I don't have a problem with it anymore but I can work on aliasing this for us Muricans who spell words in an ass backwards way.

**Comment by nmbradford** [comment]
haha - yeah - feel free to submit a PR, I just couldn't resist the opportunity to have a dig  :)
