### ISSUE TITLE
Connect-NsxServer returns error Property 'DontShow' cannot be found for type 'System.Management.Automation.ParameterAttribute'.

### ISSUE THREAD

**Issue by anksos** [vmware/powernsx#332]
Full error here:
Property 'DontShow' cannot be found for type 'System.Management.Automation.ParameterAttribute'.
At C:\Users\ADMIN\Documents\WindowsPowerShell\Modules\powernsx\PowerNSX.psm1:3892 char:9
+         [Parameter (Mandatory=$false, ParameterSetName="vCenterServer", DontShow ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFoundForType

**Comment by pandom** [comment]
Hi Anksos,

What version of Powershell are you running?

You can share the output of $psversiontable

**Comment by anksos** [comment]
Hello pandom,

Sure,

PS C:\Users\ADMIN> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.2.9200.16481
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2

PowerCLI 6.5 RC1

Thanks

**Comment by dcoghlan** [comment]
Hi @anksos 

I've taken a quick look and it appears that we've introduced the `DontShow` parameterAttribute which is available in Powershell 4.0 and newer.

Are you in a position to be able to upgrade Powershell to version 4.0 or newer?

In the meantime, we will discuss how to handle this going forward.

Thanks
Dale

**Comment by nmbradford** [comment]
Updating with decision taken internally to preserve the PoSH 3.0 minimum requirement and expose the NSXServerHint parameter to users rather than obfuscate it.  Sorry for busting things in the meantime...
