### ISSUE TITLE
NSX Load Balancer - Drain member

### ISSUE THREAD

**Issue by pandom** [vmware/powernsx#336]
Add support for Drain Member

Member condition is Enabled, Disabled or Drain.

**Comment by alagoutte** [comment]
What do you call a Drain Member ?

**Comment by ddesmidt** [comment]
(from the NSX-v 6.3 Admin Guide):
Drain: Select the member state as Drain when you want to force the server to shut down
gracefully for maintenance. Setting pool member to drain state removes the backend server
from load balancing, but still allows to access the server and accept new persistent
connections.

**Comment by alagoutte** [comment]
Ok ! need to look the API where it is !

**Comment by alagoutte** [comment]
Need to add Set-NsxLoadBalancerPoolMember and add on Add-NsxLoadBalancerPoolMember the condition

**Comment by ddesmidt** [comment]
That's under the "LB Pool Member"

Note :Actually if you change the LB Pool Member from NSX UI from "enabled" to "drain", you can see it in the PowerNSX (see condition):

PowerCLI C:\> Get-NsxEdge $Edge_Name | Get-NsxLoadBalancer | Get-NsxLoadBalancerPool -name $LB_Pool_Name | Get-NsxLoadBalancerPoolMember -name "Web01"

memberId           : member-11
groupingObjectId   : vm-1159
groupingObjectName : Web01
weight             : 1
monitorPort        : 80
port               : 80
maxConn            : 0
minConn            : 0
condition          : drain
name               : Web01
edgeId             : edge-241
poolId             : pool-7

**Comment by pandom** [comment]
I should have populated more detail in initial Issue.

This will be a new cmdlet - set-nsxloadbalancerpool member. It will take a pipe from Get-NsxLoadBalancerPoolMember. It will take the entire object, and updated modified properties, then put it back. This is like the other set operations.

There is no specific API as it is a property of the body from Get-NsxLoadBalancer Pool member. 

Modifications to New-NSXLoadBalancerMemberSpec and Add-NsxLoadBalancerMember are required to deal with the condition.

**Comment by alagoutte** [comment]
Need also to check version (Only available on 6.3)

**Comment by alagoutte** [comment]
i start to look for add set-nsxloadbalancerpoolmember but it is more complicated because there is no API for update only a member

There is POST /api/4.0/edges/{edgeId}/loadbalancer/config/members/{memberID}
but it is only for enable/disable a member...

How to update the member ?

**Comment by nmbradford** [comment]
id try a post with a body to members/{memberID} with condition set to drain, but if that doenst work, will have to get pool , update member, post pool...

**Comment by alagoutte** [comment]
There is some other function with get (parent), update and post ?

**Comment by nmbradford** [comment]
Fixed in #357 and #358

**Comment by nmbradford** [comment]
@alagoutte I needed this for internal support so just had to get it done - at least you have an example now! :)

**Comment by alagoutte** [comment]
@nmbradford Thanks, i will look (and try) add some comment (i can push PR if you want/prefer...)
and i will continue to work on test...
