### ISSUE TITLE
New-ModuleManifest and UTF 16

### ISSUE THREAD

**Issue by alagoutte** [vmware/powernsx#345]
New-ModuleManifest feature (on Publish.ps1) generate a UTF16 (LE) File
and i get some strange stuff with git tools (it is see to binary file)

After some Google Search, it is a issue with New-ModuleManifest and Git and UTF16
https://github.com/PowerShell/PowerShell/issues/3789
https://www.powershellgallery.com/packages/ModuleBuild/0.0.3/Content/plaster/PlasterModule/InvokePlaster.ps1#906
https://github.com/Microsoft/vscode/issues/26722
...

May be convert to UTF8 ?

**Comment by nmbradford** [comment]
Is there a problem that it is causing?  The manifest should not be edited directly, so the format shouldnt be a problem.

**Comment by alagoutte** [comment]
When i clone the repo and try to use file (Import PowerNSX) (for Core or Desktop), don't work

PS /home/alagoutte/PowerNSX> Import-Module PowerNSX
Import-Module : The module manifest '/home/alagoutte/.local/share/powershell/Modules/PowerNSX/PowerNSX.psd1' could not be
processed because it is not a valid PowerShell module manifest file. Remove the elements that are not permitted: At
/home/alagoutte/.local/share/powershell/Modules/PowerNSX/PowerNSX.psd1:9 char:3
+ @{
+   ~
Missing closing '}' in statement block or type definition.
At /home/alagoutte/.local/share/powershell/Modules/PowerNSX/PowerNSX.psd1:10 char:1
+ ਍ഀഀ
+ ~~~
Unexpected token '਍ഀഀ' in expression or statement.
At /home/alagoutte/.local/share/powershell/Modules/PowerNSX/PowerNSX.psd1:59 char:33
+                'PowerCLI.ViCore')
+       

(get the same issue on Windows)

**Comment by nmbradford** [comment]
Ahhh - ok, not really the way id intended it to be used (installation script and gallery distro obfuscate this), but fair enough.  If you are testing changes to the base module, For the time being, I'd recommend loading the module file directly (not via manifest).

**Comment by alagoutte** [comment]
How to load directly file ?

What do you think to add ./build.ps1 on module folder to generate a local manifest ?
(for example build.ps1 core for generate core manifest)
and use a add to .gitignore module/PowerNSX.psd1

**Comment by nmbradford** [comment]
import-module PowerNSX.psm1 :)

yeah - i think ill break it out - the test suit currently generates an on the fly manifest, ill move that to another script and call from there.  you can run that script manually to generate if you need to.

**Comment by alagoutte** [comment]
Ok ! i waiting the script :)
