### ISSUE TITLE
Duplication when creating Universal Objects

### ISSUE THREAD

**Issue by pandom** [vmware/powernsx#347]
As discussed internally.

1 source local IP Set named ACME-NTP-Servers.

`Get-NsxIpSet ACME-NTP-Servers | % { New-NsxIpSet -Name $_.name -universal `

```
Get-NsxIpSet ACME-NTP-Servers | select name,isUniversal                                                                                                                                                   
name             isUniversal
----             -----------
ACME-NTP-Servers false      
ACME-NTP-Servers true       
ACME-NTP-Servers true  
```

Results in duplicates being made.

> the get-* cmdlets that accept a universalonly / localonly switch - default to getting from both scopes
> [10:30] 
> when getting from both - there is a 'scope' collection that the process block loops accross...
> as soon as that process block emits an object, the pipeline iterates and the new-nsxipset is executed.
> [10:31] 
> then when get iterates accross the universal scope, it does ANOTHER get (which now includes a universal!)

IPSet and Security Groups are known to be impacted currently.

**Comment by leungcl** [comment]
Got this on services as well... most likely service groups too .. 
Will use localonly switch ... Thanks

**Comment by nmbradford** [comment]
nah - is fixed.  Update.  Sorry - forgot to ref this issue?

**Comment by leungcl** [comment]
Hi Nick/Anthony,

I updated PowerNSX to the latest master branch and still I’m getting duplicates with services and service groups.
Could it be that the fix was only committed for IPSets and security groups??

Regards,
Clement

**Comment by nmbradford** [comment]
I fixed it for all affected, and there are tests for it…

Service test
```
It "Creates only a single service when used as the first part of a pipeline (#347)" {
    New-NsxService -Name "$SvcPrefix-test-347" -protocol tcp -port 1234
    $Svc = Get-NsxService "$SvcPrefix-test-347" | ForEach-Object { New-NsxService -Name $_.name -
    Protocol $_.element.applicationProtocol -port $_.element.value -Universal}
    ($Svc | measure).count | should be 1
}
```

ServiceGroup test

```
It "Creates only a single servicegroup when used as the first part of a pipeline (#347)" {
    New-NsxServiceGroup -Name "$SvcPrefix-test-347"
    $SvcGrp = Get-NsxServiceGroup "$SvcPrefix-test-347" | ForEach-Object { New-NsxServiceGroup -Name 
    $_.name -Universal}
    ($SvcGrp | measure).count | should be 1
}
```

Am I missing something?  Are you doing something different to above?

**Comment by leungcl** [comment]
Thanks Nick… let me look into it… if that’s the case, I suspect that my PowerNSX version is not getting properly updated.
Since I reinstalled powershell, powercli and powernsx, everytime I close my Powershell, the powerNSX module disappears
I’ve tried using the cmdlet and manual import and still no good.
.
I’ll see Dale tomorrow, so I’ll get him to have a squiz.. Thanks Again

**Comment by nmbradford** [comment]
That sounds like you have bigger problems.  Get-Module PowerNSX and you should have 3.0.1010 (as of this morning)

**Comment by nmbradford** [comment]
lets see if we can talk internally to resolve your issues.
