### ISSUE TITLE
Installer does not detect OS Architecture correctly due to the system locale difference

### ISSUE THREAD

**Issue by funksoul** [vmware/powernsx#35]
gwmi command used to determine the OS Architecture produces localized string as a result.
So the installation of PowerNSX might fail if the system locale is not English.

I suggest [System.Environment]::Is64BitOperatingSystem instead of gwmi because it's locale agnostic. (Known to be supported dotnet version 4 or higher)

**Comment by nmbradford** [comment]
Thanks @funksoul, Ill take a look and try and address in the next release.  Sorry for the delay in response - been afk for a month!

**Comment by nmbradford** [comment]
resolved in #69
