### ISSUE TITLE
Test : need universal TransportZone / SegmentID

### ISSUE THREAD

**Issue by alagoutte** [vmware/powernsx#350]
Test, need to have universal TransportZone and but it is only when there is Cross-vCenter

[-] Has a single universal TransportZone 1.08s
   Expected: value was {}, but should not have been the same
   at line: 58 in /home/alagoutte/PowerNSX/tests/integration/01.Environment.Tests.ps1
   58:         $tz | should not be $null
 [-] Has a single universal SegmentID range defined 626ms
   Expected: {true}
   But was:  {}
   at line: 64 in /home/alagoutte/PowerNSX/tests/integration/01.Environment.Tests.ps1
   64:         $Segment.isUniversal  | should be "true"

and look only the test LogicalRouter (03) use universal.. it is not possible to limit this check to this test ?

**Comment by nmbradford** [comment]
you can have universal tz and objects without having a second vCenter/NSX.  Yes, they are only useful in the real world for CrossVC, but for testing support for these things in PowerNSX, its fine to have one VC/NSX.  Just configure manager as primary and create the TZ so you can run the test.

**Comment by alagoutte** [comment]
Thanks, i will try !

May be add a note about this on https://powernsx.github.io/contrib/ ?
I can push some change but there is already some PR with no feedback :(
