### ISSUE TITLE
New-ModuleManifest ProjectUri requires powershell 5.0 or higher.

### ISSUE THREAD

**Issue by dcoghlan** [vmware/powernsx#351]
The ProjectUri parameter defined in the psd1 manifest files requires Powershell version 5.0, breaking backward compatibility when running test suite with Powershell 3.0 environments 

Powershelgl 5.0
https://docs.microsoft.com/en-au/powershell/module/Microsoft.PowerShell.Core/New-ModuleManifest?view=powershell-5.0

Powershell 3.x and 4.x do not have this parameter
https://docs.microsoft.com/en-au/powershell/module/Microsoft.PowerShell.Core/New-ModuleManifest?view=powershell-4.0
https://docs.microsoft.com/en-au/powershell/module/Microsoft.PowerShell.Core/New-ModuleManifest?view=powershell-3.0

``` 
C:\Users\Administrator\Documents\git\dcoghlan_powernsx\tests> import-module .\Test.psd1
New-ModuleManifest : A parameter cannot be found that matches parameter name 'ProjectUri'.
At C:\Users\Administrator\Documents\git\dcoghlan_powernsx\tests\Test.psm1:30 char:119
+ ... lVersion '3.0' @Common
+                    ~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-ModuleManifest], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.NewModuleManifestCommand
```

**Comment by nmbradford** [comment]
is it just new-modulemanifest with a -projecturi argument that is breaking on < 5.0, or module import of a manifest that includes a projecturi.  I tested the later, so Id be surprised....  IF the former, we can edit the test module to remove that argument - the manifest it generates is just for the test run so doesnt really matter.

**Comment by dcoghlan** [comment]
It seems to be the new-modulemanifest with the -projecturi parameter within the test module that fails.

Options

1. Detecting Powershell version in test module and removing it from the hash table prior to splatting if version is less than 5
2. Big hammer approach and modify test module to remove it from the hash table prior to splatting, regardless of the version.

**Comment by nmbradford** [comment]
I just removed it regardless, its not required for test functionality
