### ISSUE TITLE
Need Script to display the NSX IP sec VPN Status and Statistics

### ISSUE THREAD

**Issue by vTechworld** [vmware/powernsx#353]
HI All, 

Need help in getting the NSX IP sec Statistics using script.  
![ip sec vpn statitics](https://user-images.githubusercontent.com/29917915/29205127-8b063336-7e98-11e7-8578-493c9c70f65b.png)

I am able to get the status up to VPN  using this command but not able to get the IPsec VPN Statistics as per the attached screen shot.  
$nsxvpnedge = Get-NsxEdge | where {$_.Name -match ("vpn")}
$nsxvpnedge.features.ipsec.sites.site

Please help me in getting this.

Thank you 
Nandeesh M

**Comment by alagoutte** [comment]
Hi,
it is because you need to get Ipsec Statistics and it is a another API call and it is not available for the moment...

**Comment by vTechworld** [comment]
Hi,
Thank you very much for update.

Could you please let me know where I need to add this command.  Or if you have script Please share me 
(Get-NsxEdge edge01 | Get-NsxIPsecStats).siteStatistics.tunnelStats

**Comment by alagoutte** [comment]
You need to wait this PR #354 will be merged (or you can try to use My https://github.com/alagoutte/powernsx/tree/Add-Get-NsxIPsecStats )

**Comment by vTechworld** [comment]
Hi,

I am able to get the Get-NsxIPsecStats command.  But the problem what I faced here the command is not giving any result.

(Get-NsxEdge "edge-51" | Get-NsxIPsecStats).siteStatistics.ikeStatus

This is the command I executed and there is not result.
![image](https://user-images.githubusercontent.com/29917915/29349422-7a11b5c2-8277-11e7-9bca-43e9681d283c.png)

Could you please help me on this.

Thank you,

**Comment by vTechworld** [comment]
Hi Alexis La Goutte,

I am able to get the output of the scripts. the problem what I done is instated of checking each IPsec I was checking multiple edge due that is not able to show the result. 

I changed it to single VPN IPsec and able to get the result of both ikestatus and tunnelstatus

Thank you very much for helping me the get the result. 

Thank you Thank you. :+1: :+1: :+1: :100:

**Comment by vTechworld** [comment]
Happy to work on POWERNSX

**Comment by alagoutte** [comment]
Need to merge the code now :-) (need to finish my test..)

**Comment by alagoutte** [comment]
Hi @waliapulkit 
Do you have re import the module? (and -force for reload)

**Comment by waliapulkit** [comment]
> Hi @waliapulkit
> Do you have re import the module? (and -force for reload)

Hi @alagoutte ,
I tried re import module with -force as well, still it doesn't seem to be working. Looks like my enviroment is mixed up with vmware branch and your branch, I will clean up everything once.

I will appreciate if you can provide a step by step documentation process to access and use your branch.

Thanks.

**Comment by alagoutte** [comment]
@waliapulkit 
the better is will be my patch merged directly...

for use my patch
you need to clone my repo, go on the  branch
```
git checkout Add-Get-NsxIPsecStats
```
 and manually import module : 

```powershell
import-module ./module/PowerNSX.psm1
```

**Comment by waliapulkit** [comment]
@alagoutte 

Thanks, I will try this.

I was trying this instead:

$Branch="Add-Get-NsxIPsecStats";$url="https://raw.githubusercontent.com/alagoutte/powernsx/$Branch/PowerNSXInstaller.ps1"; try { $wc = new-object Net.WebClient;$scr = try { $wc.DownloadString($url)} catch { if ( $_.exception.innerexception -match "(407)") { $wc.proxy.credentials = Get-Credential -Message "Proxy Authentication Required"; $wc.DownloadString($url) } else { throw $_ }}; $scr | iex } catch { throw $_ }

**Comment by alagoutte** [comment]
and working ?

the other solution should @nmbradford @dcoghlan merge the patch :-)

**Comment by joharG** [comment]
I could do that with below blog. 

https://vcloudnotes.blogspot.com/2019/10/how-to-get-ipsec-vpn-tunnel-stats-for.html

**Comment by alagoutte** [comment]
My patch is now merged... (but there is no yet new release of PowerNSX...)

**Comment by joharG** [comment]
Yes, happy to see if it is useful for you. I know that in Power NSX it is not possible.



Thanks,
Gautam Johar |  Senior Engineer, Cloud Operations
gjohar@navisite.com<mailto:gjohar@navisite.com> | +1-978-946-8854
RDX<https://www.rdx.com/> | Navisite<https://www.navisite.com/>

**Comment by joharG** [comment]
hopefully you found it useful.
