### ISSUE TITLE
Get-NsxService returns both universal and non-universal for a particular default service

### ISSUE THREAD

**Issue by Virtualizestuff** [vmware/powernsx#367]
Just an FYI

When I upgraded NSX Manager from 6.3.0 to 6.3.2 I noticed the developers added an additional object for the default services:
For example: Get-NsxService HTTP

Will return the following: 

objectId           : application-239
objectTypeName     : Application
vsmUuid            : 42061F61-3D04-F2CF-7D5F-E953F7D39325
nodeId             : ace20e2b-972d-4c38-b625-40b1accb13e6
revision           : 19
type               : type
name               : HTTP
scope              : scope
clientHandle       : 
extendedAttributes : 
isUniversal        : false
universalRevision  : 0
inheritanceAllowed : true
element            : element

objectId           : application-f5553a5e-bfe9-45a3-a768-ed6d432ddb71
objectTypeName     : Application
vsmUuid            : 42061F61-3D04-F2CF-7D5F-E953F7D39325
nodeId             : ace20e2b-972d-4c38-b625-40b1accb13e6
revision           : 19
type               : type
name               : HTTP
scope              : scope
clientHandle       : 
extendedAttributes : 
isUniversal        : true
universalRevision  : 0
inheritanceAllowed : false
element            : element

The first object not being universal while the second is universal. 

I may look into adding a switch to the New-NsxService cmdlet that will display the regular version or the universal version. Because if I pass this service to another cmdlet it will pass both objects which won't work correctly.

**Comment by nmbradford** [comment]
@dcoghlan - is this the case, do we have default services for a new install in universalroot-0 now in 633?

@Virtualizestuff - Be aware of the changes to support Universal that are already in PowerNSX.  It sounds like you are proposing something similar to whats already there.

1. All get cmdlets that deal with objects that can be local or universally scoped default to returning both (a get does two API calls, one for local and one for universal scope and returns the union) (previously, only local objects were returned by default)
2. All get cmdlets a/a include a -UniversalOnly or -LocalOnly switch that allows the user to filter the results accordingly.
3.  All New- cmdlets a/a will create in the local (globalroot-0) scope by default.  
4.  All New- cmdlets a/a accept a -Universal switch to create in universal scope.

**Comment by Virtualizestuff** [comment]
@nmbradford Thank you for the clarification this make total sense.

**Comment by dcoghlan** [comment]
> @dcoghlan - is this the case, do we have default services for a new install in universalroot-0 now in 633?

@nmbradford Pre-canned services have been created at installation time on both globalroot-0 and universalroot-0 since the introduction of 6.2.0.

**Comment by nmbradford** [comment]
orly?  Whoops... :)
