### ISSUE TITLE
How to get the NSXbackup file report 

### ISSUE THREAD

**Issue by vTechworld** [vmware/powernsx#369]
WITH API "GET" "/api/1.0/appliance-management/backuprestore/backups"
can we get the backup report from powerNSX

**Comment by vTechworld** [comment]
I Need only to get filename, filesize, creation date for last backup.

**Comment by alagoutte** [comment]
with Get-NsxManagerBackup, you can known the Backup Configuration
but it is not (yet) possible to configure the Manager Backup and there is no API to known the Backup Status

**Comment by vTechworld** [comment]
when I run the "GET" "/api/1.0/appliance-management/backuprestore/backups"

I will get the backup files 


# Create authentication header with base64 encoding
$EncodedAuthorization = [System.Text.Encoding]::UTF8.GetBytes($nsxUser + ':' + $nsxPass)
$EncodedPassword = [System.Convert]::ToBase64String($EncodedAuthorization)

# Construct headers with authentication data + expected Accept header (xml / json)
$headers = @{"Authorization" = "Basic $EncodedPassword"}
$headers.Add("Accept", "application/json")

# Build NSX base URI
$nsxUrl = "https://$nsxHost"

# Bypass SSL certificate verification
add-type @"
    using System.Net;
    using System.Security.Cryptography.X509Certificates;
    public class TrustAllCertsPolicy : ICertificatePolicy {
        public bool CheckValidationResult(
            ServicePoint srvPoint, X509Certificate certificate,
            WebRequest request, int certificateProblem) {
            return true;
        }
    }
"@
[System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy


# Small Function to execute a REST operations and return the JSON response
function http-rest
{
   
    [CmdletBinding()]
    param(
        [
            parameter(
                Mandatory = $true,
                HelpMessage = "Specify the REST Method to use (GET/PUT/POST/DELETE)",
                ValueFromPipeline = $false
            )
        ]
        [String]
        $method,
        [
            parameter(
                Mandatory = $true,
                HelpMessage = "Specify the REST URI that identifies the resource you want to interact with",
                ValueFromPipeline = $false
            )
        ]
        [String]
        $uri,
        [
            parameter(
                Mandatory = $false,
                HelpMessage = "Specify the body content if required (PUT/POST)",
                ValueFromPipeline = $false
            )
        ]
        [String]
        $body = $null
    )

    Begin {
        # Build Url from supplied uri parameter
        $Url = "https://$nsxHost" + $uri
    }

    Process {
        # Build Invoke-RestMethod request
        try
        {
            if (!$body)
            {
                $HttpRes = Invoke-RestMethod -Uri $Url -Method $method -Headers $headers
            }
            else
            {
                $HttpRes = Invoke-RestMethod -Uri $Url -Method $method -Headers $headers -Body $body -ContentType "application/xml"
            }
        }
        catch {
            Write-Host -ForegroundColor Red "Error connecting to $Url"
            Write-Host -ForegroundColor Red $_.Exception.Message
        }

        # If the response to the HTTP request is OK,
        # Convert it to JSON before returning it.
        if ($HttpRes) {
            $json = $HttpRes | ConvertTo-Json
            return $json
        }
        else
        {
            Write-Host -ForegroundColor Red "Error retrieving response body for $Url"
        }
    }
    End {
        # What to do here ?
    }
}
Write-Host
Write-Host -ForegroundColor Green "Query backup file"
http-rest "GET" "/api/1.0/appliance-management/backuprestore/backups" | Out-file G:\BACKUP\NsxManagerBackupStatus\NSXManagerBackup_Report\P2_NSXManagerbackup\P2_BR1_London_NSXMbackup_File$(get-date -f yyyy-MM-dd-HH-mm-ss).txt

[P2_WD1_Washington_NSXMbackup_File2017-08-22-04-30-07.txt](https://github.com/vmware/powernsx/files/1240806/P2_WD1_Washington_NSXMbackup_File2017-08-22-04-30-07.txt)

**Comment by vTechworld** [comment]
I need get only the last run file result. The txt file contains all the backup of the data.

**Comment by nmbradford** [comment]
Hey @vTechworld you are overthinking it.  Yes, there is no PowerNSX cmdlet for this yet, but you can still use it to do all the heavy lifting.  Try the following (it does everything you have above ;) : 
```
#Must connect using admin account as SSO roles are not allowed to access the appliance management apis.
Connect-NsxServer -NsxServer <yournsx> -username admin -password <admin pwd>
$uri = "/api/1.0/appliance-management/backuprestore/backups"
$backups = Invoke-NsxRestMethod -URI $uri -method get
```

Few tips.  

1. Dont work in JSON.  XML is easy to manipulate and iterate (not that JSON isnt, but its already there...)
2. Post output of ```$backups | format-xml``` once youve run this on your system and Ill help you retrieve the props you are after more easily.

**Comment by vTechworld** [comment]
I am getting the error.

Unknown data type specified as xml to Format-Xml.
At C:\Program Files\Common Files\Modules\PowerNSX\PowerNSX.psm1:3016 char:13
+             throw "Unknown data type specified as xml to Format-Xml."
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unknown data ty... to Format-Xml.:String) [], RuntimeException
    + FullyQualifiedErrorId : Unknown data type specified as xml to Format-Xml.

**Comment by nmbradford** [comment]
ok - sorry - I was assuming too much. 

```
Connect-NsxServer -NsxServer <yournsx> -username admin -password <admin pwd>
$DefaultNSXConnection.debuglogging = $true 
$uri = "/api/1.0/appliance-management/backuprestore/backups"
Invoke-NsxRestMethod -URI $uri -method get
``` 
Send me the content of the file indicated by $DefaultNSXConnection.DebugLogFile (if you dont want to paste here, send to nbradford at vmware dot com)

**Comment by nmbradford** [comment]
How did you go?

**Comment by vTechworld** [comment]
Hi Bradford, 

Sorry I was completely on leave 
Connect-NsxServer -NsxServer 10.x.x.x -username admin -password xxxxxxx
$DefaultNSXConnection.debuglogging = $true 
$uri = "/api/1.0/appliance-management/backuprestore/backups"
$inv = Invoke-NsxRestMethod -URI $uri -method get  
 $global:nreport = @()
	foreach ($nsxctrls in $inv)
		{
		$n = @{} | select filename,filesize,creationtime
		$n.filename = $nsxctrls.filename
		$n.filesize = $nsxctrls.filesize
		$n.creationTime = $nsxctrls.creationTime
		$global:nreport += $n
		}
	$global:nreport | sort LastWriteTime -Descending

this script works fine

I will get entire BACKUP report . I need last date backup only.  Could you please help me on this, 


filename     : axbr1pnsx0001-bkup22_00_00_Sat05Nov2016
filesize     : 86466592
creationtime : 1478383200000

filename     : axbr1pnsx0001-bkup22_00_00_Tue22Nov2016
filesize     : 90490912
creationtime : 1479852000000

filename     : axbr1pnsx0001-bkup22_00_00_Fri09Jun2017
filesize     : 102666272
creationtime : 1497045600000

filename     : axbr1pnsx0001-bkup22_00_00_Wed11Jan2017
filesize     : 89753632
creationtime : 1484172000000

filename     : axbr1pnsx0001-bkup22_00_00_Sat29Jul2017
filesize     : 109342752
creationtime : 1501365600000

filename     : axbr1pnsx0001-bkup22_00_00_Thu02Mar2017
filesize     : 91013152
creationtime : 1488492000000

filename     : axbr1pnsx0001-bkup22_00_00_Tue04Oct2016
filesize     : 85360672
creationtime : 1475618400000

filename     : axbr1pnsx0001-bkup22_00_00_Fri21Apr2017
filesize     : 103403552
creationtime : 1492812000000

filename     : axbr1pnsx0001-bkup22_00_00_Wed23Nov2016
filesize     : 90429472
creationtime : 1479938400000

filename     : axbr1pnsx0001-bkup22_00_00_Sat10Jun2017
filesize     : 103219232
creationtime : 1497132000000

filename     : axbr1pnsx0001-bkup22_00_00_Thu12Jan2017
filesize     : 89088032
creationtime : 1484258400000

filename     : axbr1pnsx0001-bkup22_00_00_Sun30Jul2017
filesize     : 109322272
creationtime : 1501452000000

filename     : axbr1pnsx0001-bkup22_00_00_Fri03Mar2017
filesize     : 91166752
creationtime : 1488578400000

filename     : axbr1pnsx0001-bkup22_00_00_Wed05Oct2016
filesize     : 85616672
creationtime : 1475704800000

filename     : axbr1pnsx0001-bkup22_00_00_Sat22Apr2017
filesize     : 103331872
creationtime : 1492898400000

filename     : axbr1pnsx0001-bkup22_00_00_Thu24Nov2016
filesize     : 89978912

**Comment by vTechworld** [comment]
Hi Bradford,
Could you please take a look on my query.

Thanks
Nandeesh

**Comment by dcoghlan** [comment]
@vTechworld This will get you the latest backup creation date and time in Epoch which you can convert to a standard Date/Time.
```
Connect-NsxServer -NsxServer <yournsx> -username admin -password <admin pwd>
$uri = "/api/1.0/appliance-management/backuprestore/backups"
$backup = Invoke-NsxRestMethod -URI $uri -method get
$latest = $backups.list.backupFileProperties | select-object creationTime | Sort-Object -Descending | Select-Object -First 1
$latest
```

**Comment by nmbradford** [comment]
thanks @dcoghlan.  @vTechworld does this answer your question?

**Comment by vTechworld** [comment]
Hi @daleolds @nmbradford  No luck i didn't get any output

**Comment by vTechworld** [comment]
Thanks all for supporting
