### ISSUE TITLE
How to get the Host Preparation and Service Deployments

### ISSUE THREAD

**Issue by vTechworld** [vmware/powernsx#385]
Hi Bradford, 

Hope you are doing good.

I need your help in getting the host preparation and Service Deployments report suing powernsx. 
Please help me on this.

Thank you
vTechWorld

**Comment by dcoghlan** [comment]
@vTechworld Take a look at vCheck as it may provide some/all of what you are looking for
https://vcheck.report

**Comment by nmbradford** [comment]
you can get host prep status with ```get-cluster | Get-NsxClusterStatus```

USVM management is not yet part of PowerNSX, but as @dcoghlan pointed out, vCheck might have some joy for you.

Suggest you spend a few minutes exploring the available cmdlets in the PowerNSX module ( ```get-command -module powernsx``` ) and reading the help pages associate with each cmdlet ( ```get-help <cmdlet> -detailed``` ).
