### ISSUE TITLE
Delete of SSL VPN config from ESG

### ISSUE THREAD

**Issue by neilcat** [vmware/powernsx#403]
I've looked in the PowerNSX module but cannot see anywhere this is implemented. 

Is there a PowerNSX function that does the equivalent of : 
DELETE https://NSX-Mgr-IP/api/4.0/edges/edge-XX/sslvpn/config/ 

Cheers,
Neil

**Comment by nmbradford** [comment]
not currently.  Set-NsxSslVpn puts to that URI, but there is no 'Remove-NsxSslVPN' cmdlet.  I can add it easily.  In the meantime, ```invoke-nsxrestmethod -method delete -uri '/api/4.0/edges/edge-XX/sslvpn/config/'``` should suffice for you.

**Comment by neilcat** [comment]
Thank Nick, I'll code a workaround for now. If it can be included that would be great :)

Cheers,
Neil.
