### ISSUE TITLE
Select VMs attached to a Logical Switch

### ISSUE THREAD

**Issue by Arthur-vMotion** [vmware/powernsx#409]
Hello Everyone,
I am working on a NSX and SRM integration. We have two DCs and at each location there are different number of LSs, firewall rules, etc. For the SRM to work I have to have the LSs match on both sites.
I have generatated a list of logical switches on each site, but also need to document the VMs attached to each entity.
Is there a way to do it?

Thank you.
Regards,

**Comment by nmbradford** [comment]
The process is trivial - you can just get the backingpg objects behind the LS and use powercli to do the work.

Something like the following should work (note I didn't test this, so its probably broken, but I hope you get the idea! ) - depending on what data you want out, you will probably want to manipulate the members of the pscustomobject that it emits
```
$nsxa = connect-nsxserver -vCenterServer vc_sitea -DefaultConnection:$false -VIDefaultConnection:$false
$nsxb = connect-nsxserver -vCenterServer vc_siteb -DefaultConnection:$false -VIDefaultConnection:$false
foreach ($connection in ($nsxa, $nsxb) { 
    $defaultNsxConnection = $connection
    $defaultViServer = $connection.viConnection
    foreach ( $ls in get-nsxlogicalswitch ) {
        $pg = $ls | get-nsxbackingportgroup
        foreach ( $portgroup in $pg) { 
            $vm = $portgroup| get-vm
            foreach ( $virtualmachine in $vm) { 
                 [pscustomobject]@{
                    "vCenter" = $defaultViServer.name
                    "NSX" = $defaultNsxConnection.server
                    "LogicalSwitch" = $ls.name
                    "BackingPortGroup" = $portgroup.name
                    "VirtualMachine" = $virtualmachine.name
                 }
            }
        }
    }
}
```

**Comment by Arthur-vMotion** [comment]
Good morning Nick,

Thank you very much for your response.
Please excuse my lack of lnowledge but why the Get-NSXLogicalSwitch cmdlet
does not accept piping. I mean Get-NSXLogicalSwitch | Get-VM ?

Similar to Get-Cluster "London" A Get-VM | Where .... etc.

Thank you.
Kind Regards,
