### ISSUE TITLE
NSX Licensing Problem

### ISSUE THREAD

**Issue by hakkurt** [vmware/powernsx#417]
When I try to install license with following code ;

	$ServiceInstance = Get-View ServiceInstance
        $LicenseManager = Get-View $ServiceInstance.Content.licenseManager
        $LicenseAssignmentManager = Get-View $LicenseManager.licenseAssignmentManager
        $LicenseAssignmentManager.UpdateAssignedLicense("nsx-netsec",$global:NsxlicenseKey,$NULL)
		
		$CheckLicense = $LicenseAssignmentManager.QueryAssignedLicenses("nsx-netsec") 
		$CheckLicense.AssignedLicense 
        
		write-host -foregroundcolor Green "Complete`n"

I'm getting following error ; (version 6.3.4)

Installing NSX License...
Exception calling "UpdateAssignedLicense" with "3" argument(s): "License not available to perform
the operation. The NSX for vShield Endpoint license assigned to vCenter Solution NSX for vSphere
has expired. Recommend updating the license."
At C:\Scripts\NSX-V-AutoDeploy.ps1:184 char:9
+         $LicenseAssignmentManager.UpdateAssignedLicense("nsx-netsec",$global:Nsx ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : VimException

LicenseKey : 4J6VQ-DTHEQ-58TX9-00AU6-3T952
EditionKey : nsx.vshield.cpuPackage
Name       : NSX for vShield Endpoint
Total      : 0
Used       :
CostUnit   : cpuPackage
Properties : {ProductName, ProductVersion, FileVersion, feature...}
Labels     :

Complete

**Comment by nmbradford** [comment]
hi @hakkurt I can only assume that you are using an invalid or missing license key in $global:NsxLicenseKey, but the code above is not PowerNSX (its PowerCLI).  You can see a working example in https://github.com/vmware/powernsx/blob/master/Examples/NSXBuildFromScratch.ps1.  This has been validated with a 6.3.4 deployment and a valid key.

**Comment by hakkurt** [comment]
You're exactly right. I just realized that I used an expired license. I used a valid license and It's working now. Thanks
