### ISSUE TITLE
New-NsxIpPool  DnsServer parameters

### ISSUE THREAD

**Issue by hakkurt** [vmware/powernsx#418]
When I remove DNS server parameter settings from New-NsxIpPool cmdlet (Since DNS server is not mandatory for IP pools), New-NsxController fails because of -IpPool parameter

**Comment by nmbradford** [comment]
Can you please post the code you are using that fails, and the failure message?

**Comment by hakkurt** [comment]
Hi Nick,

It worked this time. Sorry for taking your time. Here is my code ;

try {
		 
			$cluster = Get-Cluster -Name $global:VMCluster -errorAction Stop		
			$datastore = Get-Datastore -Name $global:VMDatastore -errorAction Stop
			$PortGroup = Get-VdPortGroup $global:ControllerNetworkPortGroupName -errorAction Stop
			
			$ControllerPool = Get-NsxIpPool -Name "Controller Pool"
			
			if(!$ControllerPool){		 
				write-host "   -> Creating IP Pool for Controller addressing"
				$ControllerPool = New-NsxIpPool -Name "Controller Pool" -Gateway $global:ControllerNetworkGateway -SubnetPrefixLength $global:ControllerNetworkSubnetPrefixLength -StartAddress $global:ControllerPoolStartIp -EndAddress $global:ControllerPoolEndIp 
			}
			
			for ( $i=1; $i -le $global:NumberOfController; $i++ ) {

				write-host "   -> Deploying NSX Controller $($i)"

				$Controller = New-NsxController -IpPool $ControllerPool -Cluster $cluster -datastore $datastore -PortGroup $PortGroup  -password $global:ControllerPassword -confirm:$false -wait
			 
				write-host "   -> Controller $($i) online."
			}
		}
		catch {

        Throw  "Failed deploying controller Cluster.  $_"
		}
