### ISSUE TITLE
Set-NsxEdgeFirewall need to set -NoConfirm or -Confirm to work

### ISSUE THREAD

**Issue by alagoutte** [vmware/powernsx#421]
if you use Set-NsxEdgeFirewall without (no)confirm parameter, you get the following warning : 

PS /home/alagoutte/powernsx> Get-NsxEdge Edge01 | Get-NsxEdgeFirewall | Set-NsxEdgeFirewall -Enabled        Set-NsxEdgeFirewall : Parameter set cannot be resolved using the specified named parameters.                  
At line:1 char:46
+ ... NsxEdge Edge01 | Get-NsxEdgeFirewall | Set-NsxEdgeFirewall -Enabled
+                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (System.Xml.XmlElement:XmlElement) [Set-NsxEdgeFirewall], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Set-NsxEdgeFirewall

You need to use -NoConfirm or -Confirm:$false to work

**Comment by alagoutte** [comment]
@nmbradford can you look ?

**Comment by nmbradford** [comment]
Will do in the course of bug fixes leading up to next release.  Feel free to submit a PR to fix.

**Comment by alagoutte** [comment]
I don't have really a idea to fix but i will look...

**Comment by alagoutte** [comment]
Thanks @dcoghlan #487 fix this issue...
