### ISSUE TITLE
fwenabled parameter

### ISSUE THREAD

**Issue by hakkurt** [vmware/powernsx#428]
is there any way to disable ESG firewall after ESG created ?

**Comment by alagoutte** [comment]
Hi,

There is not really a cmdlet (with a option for this)
but if you look set-nsxedge example, there is what do you need : 

    PS C:\> $edge = Get-NsxEdge Edge01
    PS C:\> $edge.features.firewall.enabled = "false"
    PS C:\> $edge | Set-NsxEdge

**Comment by hakkurt** [comment]
Thanks
