### ISSUE TITLE
No change ESG or DLR admin password from PowerNSX

### ISSUE THREAD

**Issue by kevsterd** [vmware/powernsx#431]
Whilst it is possible to change credentials from GUI or API, PowerNSX does not expose the <password> element of <cliSettings> meaning passwords cannot be changed.

**Comment by alagoutte** [comment]
Hi,

Can you try 
PS C:\> $edge = Get-NsxEdge Edge01
PS C:\> $edge.cliSettings.password = "MySuperVmware1!Password"
PS C:\> $edge | Set-NsxEdge

**Comment by kevsterd** [comment]
Nope.  I'd tried that.   Get a property 'password' cannot be found on this object.

If you look at the XML returned from an ESG there is no password shown, although I know via the actual API/Curl you can submit to /api/4.0/edges/EDGEID/clisettings with a password element.

**Comment by alagoutte** [comment]
Ok, need to add a XML Element

**Comment by nmbradford** [comment]
@kevsterd - try this - it uses the add-xmlelement PowerNSX internal function to make adding simple text elements easy as @alagoutte is eluding to.
```
#Get the edge you want to modify
$edge = get-nsxedge myedge

#Add the xml text element to the cliSettings element
Add-XmlElement -xmlRoot $Edge.CliSettings -xmlElementName "password" -xmlElementText "SuperSecretPassword!VMware1!"

#Show it (optional)
$edge.cliSettings.password
SuperSecretPassword!VMware1!

#Push update back to API. (Note you will get an error if the pwd does not meet complexity requirements)
$edge | Set-NsxEdge
```

**Comment by kevsterd** [comment]
@nmbradford Yes that appears to work.  Handy method to use where functions don't exist for other elements.

Whilst a lot of sites don't probably need it, it may be a nice to have along with the banner text and others.

**Comment by alagoutte** [comment]
i will try to implement a Get-clisettings / Set-cliSettings (but in next week...)

**Comment by alagoutte** [comment]
Hi @kevsterd 

i have push a PR with 2 new cmdlets to work with cliSettings

**Comment by kevsterd** [comment]
@alagoutte did this ever get integrated ?
