### ISSUE TITLE
Change ipset and security group scope

### ISSUE THREAD

**Issue by hakkurt** [vmware/powernsx#432]
I'm trying to change scope of ipsets and security groups

IPSET named DC_test-3 scope is Datacenter and IPSET named ipset-1 scope is Global. When I query both scope field shown as scope. Is there a way to change scope of objects ?

PowerCLI C:\> Get-NsxIpSet -name DC_test-3

objectId           : ipset-3
objectTypeName     : IPSet
vsmUuid            : 420D32AC-41DA-DE14-094F-81F12130F0EB
nodeId             : 420D32AC-41DA-DE14-094F-81F12130F0EB
revision           : 2
type               : type
name               : DC_Test-3
scope              : scope
clientHandle       :
extendedAttributes :
isUniversal        : false
universalRevision  : 0
inheritanceAllowed : false
value              : 1.1.1.21-1.1.1.30

PowerCLI C:\> Get-NsxIpSet -name test-1

objectId           : ipset-1
objectTypeName     : IPSet
vsmUuid            : 420D32AC-41DA-DE14-094F-81F12130F0EB
nodeId             : 420D32AC-41DA-DE14-094F-81F12130F0EB
revision           : 1
type               : type
name               : test-1
scope              : scope
clientHandle       :
extendedAttributes :
isUniversal        : false
universalRevision  : 0
inheritanceAllowed : true
value              : 1.1.1.1-1.1.1.10

**Comment by dcoghlan** [comment]
Unfortunately the scope is not a configuration property within NSX which you can modify directly, which also means that its impossible to just modify the scope of objects.

If you want to migrate your objects from global to universal, it requires that you re-create the object in the required scope.

For ipsets, this will be simple, as they are constructed the same, its only the scope that is different. The issue will be when you tackle security groups as there are configurations and objects which cannot be used when configuring a universal security group.

Does this help you at all?

**Comment by hakkurt** [comment]
Hi Dale,
Actually we need such a feature after a vCNS to NSX upgrade. Fortunately, we found a KB https://kb.vmware.com/kb/2117821 to solve this problem. Thanks for your comment
