### ISSUE TITLE
Ability to create NSX IPSEC Tunnels using PowerCLI or Powershell

### ISSUE THREAD

**Issue by triplej73** [vmware/powernsx#438]
Customer looking for a way to automate the creation/ updating of NSX IPSEC Tunnels using the NSX API via PCLI or Powershell.

**Comment by alagoutte** [comment]
Hi,

It is not yet available...

**Comment by pandom** [comment]
Thanks @alagoutte - I asked for this to be put here.

Thanks for submitting this.

**Comment by alagoutte** [comment]
@pandom i think work on this when my different will be merged ;-)

**Comment by pandom** [comment]
Sure, but I am not responsible for merging.

**Comment by triplej73** [comment]
Any updates @pandom @alagoutte

**Comment by alagoutte** [comment]
it is always on my TODO list...

**Comment by BasvanH** [comment]
Would love to see IPSEC support.
