### ISSUE TITLE
Clone NSX Edge/NAT

### ISSUE THREAD

**Issue by mikefoley** [vmware/powernsx#44]
In a lab situation where you are using multiple NAT Edge's to isolate duplicate lab environments (think Hands On Labs as an example), the ability to clone a template NSX NAT Edge would come in quite handy. The only think that should need to be changed is the external IP address of the Edge.

**Comment by pandom** [comment]
I believe this command is being scoped for creation. Nick and I discussed this at length (and at various decibels).

To give you an distillation of the discussion

* If you made the initial edge using PowerNSX (ie a script) then using loops or modifying a cmdlet's parameter is easy (such as uplink)
* If you didnt make the initial edge via a script your suggestion of Copy-Nsxedge is useful.

We both seasawed in both sides as there is a lot of this function that could be created by a script. It just 'depends' on what camp you're in.

Just an update.

**Comment by nmbradford** [comment]
Ok - so Ive been stealthing on this one for a few weeks, it turned out to be pretty huge.  Initial attempt has just been merged to master.  Check it out and please provide feedback.
