### ISSUE TITLE
NSX Environment Monitoring 

### ISSUE THREAD

**Issue by kakollu007** [vmware/powernsx#441]
Hi Giants ,

Could you please suggest me how to monitor the NSX environment , 

Like : getting status of  NSX edge,  manager,Controllers,Load balancers. and how to automate this monitoring through PowerNsx /RestAPI

**Comment by nmbradford** [comment]
Recommend you look at all the get-* cmdlets in PowerNSX and review the information retrieved against your monitoring needs.
