### ISSUE TITLE
<staticRouting> <gatewayAddress>??

### ISSUE THREAD

**Issue by mikefoley** [vmware/powernsx#45]
[staticRouting]
        [defaultRoute]
          [vnic]0[/vnic]
          [mtu]1500[/mtu]
          [gatewayAddress]10.x.x.x[/gatewayAddress]

There doesn't seem to be a way to set this gateway address in the New-NSXEdgeInterfaceSpec cmdlet. This is the IP of the gateway that the Uplink IP address uses. Maybe I messed something up?

**Comment by nmbradford** [comment]
Its not an interface specific configuration - its part of the static route config of the edge.  Check get-help Set-NsxEdgeRouting

**Comment by mikefoley** [comment]
Ah-ha! I guess I have more work to do on that script. :) :) 

Cheers mate.
