### ISSUE TITLE
PowerNSX fails to register vcenter when used against NSX 6.4.0

### ISSUE THREAD

**Issue by nmbradford** [vmware/powernsx#458]
```
PowerCLI C:\> Set-NsxManager -vCenterServer vc-01a.corp.local -vCenterUserName administrator@vsphere.local -vCenterPassword VMware1! -AcceptAnyThumbprint

Invoke-NsxRestMethod : The NSX API response received indicates a failure. 400 : Bad Request : Response Body: <?xml version="1.0" encoding="UTF-8"?>
<error><errorCode>226</errorCode><details>43:FE:C5:04:90:A7:F6:2D:9F:BB:35:0E:49:DF:3E:62:A8:6E:64:1C:87:FB:95:42:1B:43:80:3B:F7:BC:DA:E8</details></
error>
At C:\Users\Administrator\Documents\WindowsPowerShell\Modules\PowerNsx\PowerNSX.psm1:4108 char:13
+             throw $ErrorString
+             ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Invoke-NsxRestM...etails></error>:String) [], RuntimeException
    + FullyQualifiedErrorId : Invoke-NsxRestMethod : The NSX API response received indicates a failure. 400 : Bad Request : Response Body: <?xml ver
   sion="1.0" encoding="UTF-8"?>
    <error><errorCode>226</errorCode><details>43:FE:C5:04:90:A7:F6:2D:9F:BB:35:0E:49:DF:3E:62:A8:6E:64:1C:87:FB:95:42:1B:43:80:3B:F7:BC:DA:E8</detai
   ls></error>
```

**Comment by nmbradford** [comment]
Issue is with internal test-webserverssl function that does not return the correct thumbprint for nsx 6.4.0.  Also - the error return includes the thumbprint presented by the server so just need to update to use that if returned.

**Comment by EleanorRigby** [comment]
I got stuck at same error. It seems the vCenter thumbprint accepted by NSX `6.3.x` is `SHA1` while the one accepted by `6.4.x` is `SHA256`

**Comment by EleanorRigby** [comment]
the one returned here 
```
<error><errorCode>226</errorCode><details>43:FE:C5:04:90:A7:F6:2D:9F:BB:35:0E:49:DF:3E:62:A8:6E:64:1C:87:FB:95:42:1B:43:80:3B:F7:BC:DA:E8</details></
error>
```
is `SHA256` because you might have sent `SHA1` by mistake or because of faulty test-webserverssl function.

**Comment by EleanorRigby** [comment]
Just wanted to leave these notes for future developers looking into this bug

**Comment by JoseIbanez** [comment]
my work arround:

try {
    $vc = Set-NSXManager -vCenterServer $vcFQDN -vCenterUserName $vcUsername -
vCenterPassword $vcPasswordPlain
} catch {
    $ErrorMessage = $_.Exception.Message
}
$ErrorMessage -match 'details":"(?<key>.*)","'
$sslThumbprint=$matches['key']
$sslThumbPrint
$vc = Set-NSXManager -vCenterServer $vcFQDN -vCenterUserName $vcUsername -vCenterPassword $vcPasswordPlain -SslThumbprint $sslThumbPrint

**Comment by dwchan69** [comment]
I try the code as it, the -match syntax did not work.  In addition, when I copy and paste the SSL thumbprint from my error directly back into the set-nsxmanager command, it still fail
