### ISSUE TITLE
Help for Get-NsxUserRole has text for Get-NsxLogicalSwitch

### ISSUE THREAD

**Issue by neilcat** [vmware/powernsx#475]
PowerCLI C:\> get-help Get-NsxUserRole

NAME
    Get-NsxUserRole

SYNOPSIS
    Retrieves a Logical Switch object

SYNTAX
    Get-NsxUserRole [-UserName] <String> [-Connection <PSObject>] [<CommonParameters>]

DESCRIPTION
    An NSX Logical Switch provides L2 connectivity to VMs attached to it.
    A Logical Switch is 'bound' to a Transport Zone, and only hosts that are
    members of the Transport Zone are able to host VMs connected to a Logical
    Switch that is bound to it.  All Logical Switch operations require a
    Transport Zone.

**Comment by alagoutte** [comment]
Hi Neil,

i found also the issue and forget to make a PR...

**Comment by nmbradford** [comment]
Thanks for reporting Neil!  Thanks for PR Alexis!
