### ISSUE TITLE
PowerNSXInstaller supports user's module path without need for admin permissions

### ISSUE THREAD

**Issue by matt232h** [vmware/powernsx#48]
The need for admin permissions can be avoided if the user's PowerShell module path is used rather than the common system module path.

**Comment by nmbradford** [comment]
Resolved in PR #89.  Added -InstallType AllUsers/CurrentUser, with the default being CurrentUser and removed the checks for elevation unless required by AllUsers installtype.

Please test and let me know if there are any issues.
