### ISSUE TITLE
PowerNSX don't work with Powershell 6.0.(1) and PowerCLI 10

### ISSUE THREAD

**Issue by alagoutte** [vmware/powernsx#483]
When i try to use PowerNSX 3.0(.1085) on [powershell 6.0(.1)](https://github.com/PowerShell/PowerShell/releases/tag/v6.0.1) and new [PowerCli 10](https://blogs.vmware.com/PowerCLI/2018/02/powercli-10.html) on Ubuntu 16.04

I get the following warning : 
```
PS /home/alagoutte> Import-Module PowerNSX
WARNING: This build of PowerShell core has known issues that affect PowerNSX.  The only recommended  build of PowerShell Core at this stage is alpha-18.
Import-Module : The PowerShell Core Beta has known issues that cause PowerNSX to fail.  Refusing to load module.
At line:1 char:1
+ Import-Module PowerNSX
+ ~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (The PowerShell ...to load module.:String) [Import-Modu le], RuntimeException
+ FullyQualifiedErrorId : The PowerShell Core Beta has known issues that cause PowerNSX to fail.  Refusing to load module.,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by alagoutte** [comment]
i have try to remove version check but now it is not longer different module name for PowerCLI... (use the same module like Desktop...)

**Comment by dcoghlan** [comment]
If you need to get it running urgently, you can install the module from the gallery using Install-Module PowerNSX, which will pass the module dependency check, as like you mentioned, the modules are now named the same between the desktop and core versions of PowerCLI, then take a look at #485 to see the changes you can make to the PowerNSX.psm1 file itself to get it to load and have some basic functionality.

I'm just running some CI testing to make sure that the changes don't break backward compatibility with the Alpha.18 release of Powershell core for the time being. I will speak with the team on how we handle the manifests for each version (core/desktop & gallery)

**Comment by alagoutte** [comment]
It is better now (i can launch and use powernsx) but always get error when try to launch testsuite

Import-Module : The required module 'PowerCLI.Vds' is not loaded. Load the module or remove the module from 'RequiredModules' in the file '/home/alagoutte/powernsx/PowerNSX.psd1'.

**Comment by nmbradford** [comment]
the general support for PowerCLI 10 and PoSH core 6 is address in build #1088, so Ill close this issue.  The test suite issue we will investigate internally - thanks @alagoutte alaguette
