### ISSUE TITLE
Set-NsxEdgeFirewall requires Confirm parameter but error message not descriptive

### ISSUE THREAD

**Issue by AVillarGarea** [vmware/powernsx#486]
The following command 
_Get-NsxEdge | Get-NsxEdgeFirewall | Set-NsxEdgeFirewall -DefaultRuleAction deny_

returns this error message
_Set-NsxEdgeFirewall : Parameter set cannot be resolved using the specified named parameters._

Adding _-Confirm_, it works: 
_Get-NsxEdge | Get-NsxEdgeFirewall | Set-NsxEdgeFirewall -DefaultRuleAction deny -Confirm_

Though _-Confirm_ is only an optional parameter according the get-help.

Would it be possible to update the error message and/or the command help?
Thanks!

**Comment by dcoghlan** [comment]
I can see the issue. I have submitted PR #486 which should fix the issue.
