### ISSUE TITLE
New-NsxService port requirements

### ISSUE THREAD

**Issue by pandom** [vmware/powernsx#49]
New-NSxService makes a non mandatory port field mandatory. Please make it wokr so a service can be defined by protocol alone and no ports!

**Comment by srobroek** [comment]
Bumping this issue as it is causing some of our scripts to fail. Would personally prefer accepting a -port value of "any". 

Will see if i can create a pull request later.

**Comment by nmbradford** [comment]
Already done in PR #148.  Forgot to link this issue sorry.  Can you test against latest master and let me know if you still have issues @srobroek?

**Comment by srobroek** [comment]
Yeah, i just checked my code and noticed that my installed release still has it. Just tested on master branch and it's working perfect, thanks for the quick reply :)

**Comment by nmbradford** [comment]
pleasure - glad it was an easy one!  Closing this issue now.
