### ISSUE TITLE
New-NsxEdgeNatRule missing dnatMatchSourceAddress

### ISSUE THREAD

**Issue by souhradab** [vmware/powernsx#500]
Example:  get-nsxedge edge-test | get-nsxedgenat | Get-NsxEdgeNatRule

ruleId                 : 200710
ruleTag                : 200710
ruleType               : user
action                 : dnat
vnic                   : 0
originalAddress        : 192.168.0.40
translatedAddress      : 10.120.38.40
dnatMatchSourceAddress : 10.4.33.0/24
loggingEnabled         : true
enabled                : true
description            :
protocol               : any
originalPort           : any
translatedPort         : any
dnatMatchSourcePort    : any

**Comment by souhradab** [comment]
Just noticed in the NSX API (6.3.0) the following:

Method updated. dnatMatchSourceAddress, snatMatchDestinationAddress, dnatMatchSourcePort, snatMatchDestinationPort parameters added.
protocol, originalPort, and translatedPort now supported in SNAT rules.

**Comment by alagoutte** [comment]
Hi,

Yes, missing new method from 6.3.0 !
I wrote a patch for fix this issue https://github.com/alagoutte/powernsx/tree/fix_500 but need to add more test before PR !
