### ISSUE TITLE
Disable a DFW rule

### ISSUE THREAD

**Issue by hakkurt** [vmware/powernsx#504]
Hi,
I'm working on a DFW cleanup script. My goal is creating a script that will check whole DFW rule base daily and if it found a date in comments fields older then current date, it'll automaticaly disable it (expired rule). I can get date from comment field as notes, But I could not find any cmd-let for disabling a DFW rule

Thanks in advance

**Comment by alagoutte** [comment]
Hi,

Yes, it is not possible for the moment...
i write a new cmdlet for this ! set-nsxfirewallrule
the code is available here https://github.com/alagoutte/powernsx/tree/set-nsxfirewallrule
Need to write some test before make a PR

You can use get-firewallrule -RuleId 1007 | set-nsxfirewallrule -disabled:$true

**Comment by hakkurt** [comment]
Thanks Alexis.
I temporary developed script by using Invoke-NsxWebRequest. I'll update my
script once  set-nsxfirewallrule is included PowerNSX

https://github.com/hakkurt/Scripts/blob/master/NSX-v-Scheduled-Rules/NSX-v-Scheduled-Rules.ps1

2018-04-20 15:03 GMT+03:00 Alexis La Goutte <notifications@github.com>:
