### ISSUE TITLE
NAT rules - Applied on filed is not visible when I run the command

### ISSUE THREAD

**Issue by vTechworld** [vmware/powernsx#511]
Hi Team,

While executing the script I am getting all the parameters which are in GUI only part which is not visible is Applied On
I executed both type of powernsx commands.   The result shows very good.

The filed I am looking is Applied On.  Please let me know how can I get this.

![nat rule](https://user-images.githubusercontent.com/29917915/39422148-c3b3b4e6-4c89-11e8-901a-9d47cf8d7c2c.JPG)

PS C:\> $LN2NAT | Get-NsxEdgeNat | Get-NsxEdgeNatRule | ft -AutoSize

ruleId ruleTag ruleType action vnic originalAddress  translatedAddress loggingEnabled enabled description
------ ------- -------- ------ ---- ---------------  ----------------- -------------- ------- -----------
208928 208928  user     snat   0    10.x.x.x/16    159.x.x.165     true           true    Outbound Internet connectivity for BYOIP...
208930 208930  user     snat   1    10.x.x.x     10.x.x.x    true           true    Twinstrata NAT

PS C:\> $LN2NAT | Get-NsxEdgeNat | Get-NsxEdgeNatRule | ft -AutoSize

ruleId ruleTag ruleType action vnic originalAddress  translatedAddress loggingEnabled enabled description
------ ------- -------- ------ ---- ---------------  ----------------- -------------- ------- -----------
208928 208928  user     snat   0    10.x.0.0/16    159.x.x.x     true           true    Outbound Internet connectivity for BYOIP...
208930 208930  user     snat   1    10.x.x.x     10.x.x.x    true           true    Twinstrata NAT
208931 208931  user     snat   1    10.x.x.x     10.x.x.x     true           true    Twinstrata NAT
208929 208929  user     snat   1    10.x.x.x/26 159.x.x.x     true           true    Outbound

**Comment by alagoutte** [comment]
Hi vTechWorld,

You have the information... but it is no "translated" 
it is the vnic column to get the name of vnic, you can look on $edge.vnics.vnic (look index column)

**Comment by vTechworld** [comment]
Hi Alagoutte, 

Thanks for helping out.  I am able to get the it and its looks good to figure it out. 

Happy to work on powernsx
