### ISSUE TITLE
Get-NSXEdge: Edge Version ? 

### ISSUE THREAD

**Issue by chvolcko** [vmware/powernsx#525]
Hello, 

 I have done some searching and cant seem to find the answer. When I do a Get-NSXEdge , the version returned does not seem to be of any use, and I have compared them in the environment. I am attempting to use PowerNSX to do an upgrade of older edges in our environment ,  however I cant target them by version so its pretty much useless for this task, unless I am missing something? 
![capture](https://user-images.githubusercontent.com/1272967/41867967-9df13d9e-7882-11e8-88a7-7c21f6f71ce9.JPG)

Thanks,
-Christian

**Comment by alagoutte** [comment]
Hi Christian,

version field is a "internal" field available on all NSX "object" and for each modification, there is increment of this value (it is for check if there is not a update of object before update)

for get "release" of Edge, you need to look EdgeSummary if i remember

**Comment by alagoutte** [comment]
and if you want to update Edge (ESG), you need to use Repair-NSX... ( Get-NsxEdge Edge01 | Repair-NsxEdge -Operation Upgrade ) see #454

**Comment by chvolcko** [comment]
Alexis, 
 Thank you for helping a newb out! this got me where I needed to be. I'm a big fan of PowerNSX. 

Thanks
-Christian
