### ISSUE TITLE
PowerNSX in docker?

### ISSUE THREAD

**Issue by MrCNeale** [vmware/powernsx#53]
I've been using PowerCLI on Docker on Photon recently and tried to run the installer or import the powernsx module.  However it throws errors as it's trying to check for pre-reqs in places like the windows registry.
It's not confined to docker, the same happens on powershell installed via the bintray yum repo and then with powercli modules imported.
Is it possible to change the pre-req checks or would that not help because powerclicore or powershell on linux is fundamentally missing something powerNSX requires?

**Comment by nmbradford** [comment]
Unfortunately, there is fundamental missing functionality that will prevent it working.  It is being worked on and there is a merge on at least PR in PowerShell core that I'm waiting on until I can continue testing.  It is definitely the plan to support this though.

**Comment by nmbradford** [comment]
Hi @MrCNeale - I've now done enough on this now to be sure I can get a functional version of PowerNSX core running on Linux (and hence docker instances) and should be able to do the same within a single module!  There are a number of changes that touch the core of PowerNSX though, and could potentially break a lot of things, and there is still some PowerShell core functionality that is broken/missing that I need fixed before the experience is on a par with PowerNSX as of now, so this will take some time.  I'm hoping to preview in 2.1/2.2 though via a separate module so I will enlist you when this is available to assist in testing.

**Comment by MrCNeale** [comment]
Great news, thanks for the update.  @rhancock8 and I will be happy to test!

**Comment by tsugliani** [comment]
Hey @MrCNeale,

@alanrenouf has updated the VMware PowerCLI core docker image with PowerNSX yesterday. (cf https://github.com/vmware/powerclicore/commit/22488b3999b01945392a9a6ad79a86128ff40c5d) 

you should be able to get a usable container by just fetching the https://hub.docker.com/r/vmware/powerclicore/ image that is built from that repository.

`docker pull vmware/powerclicore`

**Comment by MrCNeale** [comment]
@tsugliani great news. Will try it out this week. Thanks

**Comment by nmbradford** [comment]
unfortunately, PowerNSX requires PowerShell 6.0 alpha 13 or greater (the photon docker image for powercli is at 12) so it wont work - ill work with @alanrenouf to get this fixed asap.  In the meantime, should i release a powernsx (with powercli) image based on ubuntu, or does this muddy the waters?

**Comment by rhancock8** [comment]
Thanks for the heads up @nmbradford,  @MrCNeale, I guess it's a question of how long it may take to get the photon image up to the right level. If it's not going to be months away, I think I'd prefer to wait for that, if possible, as it would be good to have a single standard platform for us to base all of the VMware management tools on.

**Comment by nmbradford** [comment]
agreed - I spoke with @alanrenouf today and he thinks it should be fairly quick, so Ill hold off on releasing something non standard.

**Comment by alanrenouf** [comment]
Sorry for the delay, this has now been updated to PowerShell 6.0.0-alpha14 so should now work!

**Comment by nmbradford** [comment]
Ive tested today, and it looks like PowerNSX is all good, though I think I found an issue with Photon in general that causes intermittent connection failures in PowerCLI.  You can docker pull vmware/powerclicore to give it a try.  @alanrenouf is aware of the problem and I'm sure there will be an update shortly.

Log new issues for any problems you hit.
