### ISSUE TITLE
Can't  document NSX 6.3 firewall rules using DFW2Excel.ps1. Error "Unable to retreive role details from NSX.  Invoke-NsxRestMethod : The NSX API response received indicates a failure. 400 : Bad Request : Response Body: <?xml version="1.0" encoding="UTF-8"?>"

### ISSUE THREAD

**Issue by mir1218** [vmware/powernsx#531]
I am new to powernsx , I followed the instruction to connect to vcenter and nsx using sso credentials as below.
PS /> Connect-NsxServer -vCenterServer vc-01a.corp.local

Entered the SSO credential's and can retrieve the range of different information from powercli. But I tried documenting DFW rules and it throws the following error. 

Does anyone knows what's going or what I am doing wrong.
![edit123](https://user-images.githubusercontent.com/41085798/42550686-2dd394f0-84a1-11e8-956f-a148d68c4db8.png)

**Comment by alagoutte** [comment]
Hi,

Do you have with administrator account ?

Do you have check if the user have NSX privilege ?

**Comment by mir1218** [comment]
I use my account to access vcenter and configure all nsx policies . If it does not have nsx privilege then probably I could not do all those tasks. Is there anyway I could check form vcenter.

**Comment by mir1218** [comment]
I just checked its Enterprise Admin Privilege

**Comment by alagoutte** [comment]
can you try Get-NsxRole cmdlets ?

May be also need to use directly nsx-powerops tools (may be a update with a fix for this issue)

**Comment by mir1218** [comment]
PS C:\Users\xyzr\Documents\WindowsPowerShell\Scripts> Get-NsxRole 
Get-NsxRole : The term 'Get-NsxRole' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by mir1218** [comment]
![capture](https://user-images.githubusercontent.com/41085798/42663042-ebf553fe-8601-11e8-9018-fc1741be8889.PNG)

**Comment by mir1218** [comment]
I used the same user details to create visio diagrama nd to capture the data, it works like a charm . But not this script...

**Comment by alagoutte** [comment]
Sorry, it is a get-nsxuserrole

and for last error message, it is say, we need to use the local NSX Manager Account (super_user role access...)

**Comment by mir1218** [comment]
I got it, my question is there anyway to make it work with current account. It has enterprise admin access.

**Comment by alagoutte** [comment]
it is a nsx-powerops issue, need to ask directly on nsx-powerops

for a quick look of code, coming for call a function (Get-NsxManagerSystemSummary) need super_user role access may be can be change..
There is a PR for look enhance this https://github.com/vmware/nsx-powerops/pull/61

**Comment by mir1218** [comment]
Hey it works , thanks for the guidance. I really appreciate it.

**Comment by mir1218** [comment]
here is a PR for look enhance this vmware/nsx-powerops#61

**Comment by alagoutte** [comment]
i think, it will be possible to make a small fix and i will be more easy to merge...
