### ISSUE TITLE
Need help in getting the firewall details for VM

### ISSUE THREAD

**Issue by vTechworld** [vmware/powernsx#546]
WARNING: This cmdlet is experimental and has not been well tested.  Its use should be limited to troubleshooting purposes only.
get-vm : 8/14/2018 12:06:59 PM  Get-VM          [Invoke-NsxCli][ERROR] Unable to execute Centralized CLI query. Unable to parse Centralised CLI output line : rule_2693_at_121_inout_protocol_tcp_from_addrset_ip-ipset-63_to_addrset_ip-ipset-5_port_21_accept_as_ftp;.Exception.Message. Try re-running co
mmand
with the -RawOutput parameter.
At line:1 char:1
+ get-vm LJLN2PDAS0013 | Get-NsxCliDfwRule | ft -wrap -autosize
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-VM], VimException
    + FullyQualifiedErrorId : Core_BaseCmdlet_UnknownError,VMware.VimAutomation.ViCore.Cmdlets.Commands.GetVM

PS C:\>

**Comment by nmbradford** [comment]
duplicates #466
