### ISSUE TITLE
Changing VXLAN Port

### ISSUE THREAD

**Issue by zackless** [vmware/powernsx#551]
Do we support changing VXLAN Port from commands?

**Comment by alagoutte** [comment]
Hi Zack,

No there is no cmdlet for change VXLAN Port

But you can use 

`Invoke-NsxRestMethod -Method "PUT" -Uri "/api/2.0/vdn/config/vxlan/udp/port/{portNumber}?force=true"`

Replace {portNumber} by the port number 

For more info about the VXLAN Port Configuration, you need to look nsx_64_api(.pdf) guide

**Comment by zackless** [comment]
Thank you @alagoutte . Problem solved.
