### ISSUE TITLE
Powershell Core 6.1 - Module refuses to load

### ISSUE THREAD

**Issue by Zsoldier** [vmware/powernsx#557]
**The PowerShell Core Beta has known issues that cause PowerNSX to fail.  Refusing to load module.**

6.1 is general release now.  Any ideas as to where the code breaks for 6.1?  Haven't dug into it yet, but it is definitely starting to get annoying.

**Comment by nmbradford** [comment]
@dcoghlan Isnt the git commitid only included to exclude certain earlier versions of Core Beta?  We should probably make the check explicit for GA Core and remove the explicit check for commit id?

**Comment by alagoutte** [comment]
Hi,

Any news because it is blocking for some user...
Do you want i push the fix ?

**Comment by alagoutte** [comment]
Hi,

Any news ?

**Comment by dcoghlan** [comment]
This is now fixed in #568

**Comment by alagoutte** [comment]
Thanks Dale !
