### ISSUE TITLE
Debug log file lock

### ISSUE THREAD

**Issue by tlindsay42** [vmware/powernsx#57]
Frequently receiving the following error:

Add-Content : The process cannot access the file 'C:\Debug.log' because it is being used by another process.
At C:\Program Files\Common Files\Modules\PowerNSX\PowerNSX.psm1:2611 char:13
-             Add-Content -Path $Connection.DebugLogfile -Value "$(Get- ...
-             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : WriteError: (C:\Debug.log:String) [Add-Content], IOException
  - FullyQualifiedErrorId : GetContentWriterIOError,Microsoft.PowerShell.Commands.AddContentCommand

**Comment by nmbradford** [comment]
Have you got another process with a write lock on it?  I cant repro (just tested with a few common text editors).  Use something like process explorer from sysinternals suite to search for handles on the file so you can work out what process is locking it.

**Comment by nmbradford** [comment]
actually - just realised you have overridden the default debug log file path for one in the root of C:.  If you are running under UAC, this will cause issues.  I just tried (I have UAC on) and I get a more expected 'Access Denied', but check for sure you have write access to that file from a non elevated process ( you wont by default)

PS C:\Users\Nick\Documents\git\powernsx> Get-NsxLogicalSwitch                                                          
Add-Content : Access to the path 'C:\debug.log' is denied.                                                             
At C:\Users\Nick\Documents\git\powernsx\PowerNSX.psm1:2762 char:13                                                     
+             Add-Content -Path $Connection.DebugLogfile -Value "$(Get- ...                                            
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                
    + CategoryInfo          : PermissionDenied: (C:\debug.log:String) [Add-Content], UnauthorizedAccessException       
    + FullyQualifiedErrorId : GetContentWriterUnauthorizedAccessError,Microsoft.PowerShell.Commands.AddContentCommand

**Comment by tlindsay42** [comment]
I'm actually using almost exactly the same path, I just masked it so that I wasn't posting my local username on a public  thread.

Regards,-Troy
-------- Original message --------From: nmbradford <notifications@github.com> Date: 10/27/16  07:49  (GMT-06:00) To: vmware/powernsx <powernsx@noreply.github.com> Cc: Troy Lindsay <tlindsay42@gmail.com>, Author <author@noreply.github.com> Subject: Re: [vmware/powernsx] Debug log file lock (#57) 
actually - just realised you have overridden the default debug log file path for one in the root of C:.  If you are running under UAC, this will cause issues.  I just tried (I have UAC on) and I get a more expected 'Access Denied', but check for sure you have write access to that file from a non elevated process ( you wont by default)

PS C:\Users\Nick\Documents\git\powernsx> Get-NsxLogicalSwitch


Add-Content : Access to the path 'C:\debug.log' is denied.


At C:\Users\Nick\Documents\git\powernsx\PowerNSX.psm1:2762 char:13                                                     


            Add-Content -Path $Connection.DebugLogfile -Value "$(Get- ...


            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



CategoryInfo          : PermissionDenied: (C:\debug.log:String) [Add-Content], UnauthorizedAccessException


FullyQualifiedErrorId : GetContentWriterUnauthorizedAccessError,Microsoft.PowerShell.Commands.AddContentCommand 




—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/vmware/powernsx","title":"vmware/powernsx","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/vmware/powernsx"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nmbradford in #57: actually - just realised you have overridden the default debug log file path for one in the root of C:.  If you are running under UAC, this will cause issues.  I just tried (I have UAC on) and I get a more expected 'Access Denied', but check for sure you have write access to that file from a non elevated process ( you wont by default)\r\n\r\nPS C:\\Users\\Nick\\Documents\\git\\powernsx\u003e Get-NsxLogicalSwitch                                                          \r\nAdd-Content : Access to the path 'C:\\debug.log' is denied.                                                             \r\nAt C:\\Users\\Nick\\Documents\\git\\powernsx\\PowerNSX.psm1:2762 char:13                                                     \r\n+             Add-Content -Path $Connection.DebugLogfile -Value \"$(Get- ...                                            \r\n+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                \r\n    + CategoryInfo          : PermissionDenied: (C:\\debug.log:String) [Add-Content], UnauthorizedAccessException       \r\n    + FullyQualifiedErrorId : GetContentWriterUnauthorizedAccessError,Microsoft.PowerShell.Commands.AddContentCommand \r\n"}],"action":{"name":"View Issue","url":"https://github.com/vmware/powernsx/issues/57#issuecomment-256631459"}}}

**Comment by tlindsay42** [comment]
Here is an example of where someone else ran into this issue with Add-Content: https://social.technet.microsoft.com/Forums/en-US/a169b694-8996-4dcf-83b8-e3aa4ce2dff5/powershell-addcontent-errors-with-the-process-cannot-access-the-file-because-it-is-being-used?forum=ITCG

The file locks are causing content updates to start failing periodically when the debug log file grows to somewhere between 10MB and 300MB in a few seconds. 

I'm writing to a Samsung mSATA SSD, so no spinning disk.

Out-File -Append appears to be a bit more friendly per http://stackoverflow.com/questions/10655788/powershell-set-content-and-out-file-what-is-the-difference, but a FileStream may be the way to go.

**Comment by nmbradford** [comment]
Ok - thanks for the background @tlindsay42 .  I couldnt repro, but I certainly agree set/add-content was not optimal.  I've just merged pull request #60 that changes all logging output to out-file -append.  Please take a look and let me know if it resolves your issue.  The added benefit regardless is that you can now read the file while it is being written to (tail -f in Ubuntu on Windows or BareTail works now when it didnt previously).

**Comment by tlindsay42** [comment]
I'm still able to duplicate consistently, but there is some improvement with Out-File

out-file : The process cannot access the file '~\git\project\log\debug.log' because it is being used by another process.
At C:\Program Files\Common Files\Modules\powernsx\PowerNSX.psm1:2762 char:151
+ ... mat-Xml)" | out-file -Append -FilePath $Connection.DebugLogfile -Enco ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], IOException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

**Comment by nmbradford** [comment]
Can you check to find what process is locking the file?  When I tested this change, I tried thousands of continuous gets against the api to generate the quickest growing log I could think of (1..1000  | % { $null = Get-NsxService } ) which caused it to grow by 30MB per minute or so.  What are you doing to make the log grow so quickly!?  Ill need steps to reproduce or a PR that fixes your issue that I can review to take it any further.

**Comment by nmbradford** [comment]
@tlindsay42 - were you able to get more info on a repro for me?
