### ISSUE TITLE
Source parameter for "Any"

### ISSUE THREAD

**Issue by regmiboyer** [vmware/powernsx#572]
Hi Guys,

This would be a dumb question but unfortuanetly i cant find answer to it anywhere. what parameter should I use to specify any source or destination while creating a new NSX firewall rule in 6.4 using powerNSX? I am trying to use a string “Any” but that didn’t work, tried * with no luck. Same goes with Service if I want to specify any service.

**Comment by alagoutte** [comment]
Hi,
Do you have try to don't specify Source or Destination ?

**Comment by regmiboyer** [comment]
> Hi,
> Do you have try to don't specify Source or Destination ?

Hi, 

This is now resolved. All this while i was using -source "Any" or -Source "*" or -Source Any but then i tried without the -Source and it just ran. 

Thanks for your assistance.
