### ISSUE TITLE
Add-NsxLoadBalancerPoolMember Problem

### ISSUE THREAD

**Issue by eaphilipp** [vmware/powernsx#575]
Hello,

I am trying to automate a NSX LoadBalancer Pool Member add and I am using the following commandlet:

get-nsxedge TEST-LB | Get-NsxLoadBalancer | Get-NsxLoadBalancerPool -name SYSLOG  | Add-NsxLoadBalancerPoolMember -Name NODE-1-5-914 -IpAddress 9.9.9.9 -Weight 1 -MonitorPort 9001  -Port 514

Everything works except for the -Monitor Port. It is not putting 9001 it is putting 514.

What am I doing wrong?

**Comment by alagoutte** [comment]
Hi,

i look like a bug...

**Comment by eaphilipp** [comment]
OK, sorry for the dumb question, but is that something I can fix? Or?

**Comment by eaphilipp** [comment]
So I alerted the .PSM1 file. I found the bad line and it still doesn't work? I have never done this so I am not sure if there is something else I have to do? I reloaded the ISE and the modules were reloaded.

**Comment by alagoutte** [comment]
I will push a fix soon

You need to may be force reload of module
```powershell
Import-Module PowerNSX -force
```
