### ISSUE TITLE
Remove-NsxEdgeStaticRoute

### ISSUE THREAD

**Issue by officialh1** [vmware/powernsx#580]
get-nsxEdge | Get-NsxEdgeRouting | Remove-NsxEdgeStaticRoute
Should remove all static routes from all edge routers, but it fails with this error:

`Remove-NsxEdgeStaticRoute : Cannot validate argument on parameter 'StaticRoute'. XML Element specified does not
contain a type property.
At line:1 char:36
+ get-nsxEdge | Get-NsxEdgeRouting | Remove-NsxEdgeStaticRoute
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (System.Xml.XmlElement:XmlElement) [Remove-NsxEdgeStaticRoute], ParameterBi
   ndingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Remove-NsxEdgeStaticRoute`

Obviously something like this would fail as well: 

get-nsxEdge | Get-NsxEdgeRouting | Where {$_.staticrouting.staticroutes.route.network -eq "0.0.0.0/0"} | Remove-NsxEdgeStaticRoute

**Comment by alagoutte** [comment]
Hi,

From Remove-NSxEdgeSatticRoute example, missing a **Get-NsxEdgeStaticRoute**

```powershell
    .EXAMPLE
    Remove all routes to 1.1.1.0/24 from ESG Edge01
    PS C:\> Get-NsxEdge Edge01 | Get-NsxEdgeRouting | Get-NsxEdgeStaticRoute | where-object { $_.network -eq '1.1.1.0/24' } | Remove-NsxEdgeStaticRoute
```

**Comment by officialh1** [comment]
Oops, forgot a layer.
