### ISSUE TITLE
Rename Logical Switch

### ISSUE THREAD

**Issue by CernSteve** [vmware/powernsx#586]
I may be missing it but we need need to mass re-name Logical Switches. I see how to get, remove, and create but not modify. Any thoughts?

**Comment by alagoutte** [comment]
Hi Steve,

Yes, it is not possible for the moment...
but you can try this (not tested..)
```powershell
$ls = Get-NsxTransportZone | Get-NsxLogicalSwitch MyLogicalSwitch
$ls.name = "new name"
$uri = "/api/2.0/vdn/virtualwires/$($ls.ObjectId)"
Invoke-NSXWebRequest -method "put" -uri $uri -body $ls
```

**Comment by CernSteve** [comment]
Thanks for the update we'll give that a shot.

**Comment by alagoutte** [comment]
working ?

**Comment by alagoutte** [comment]
Fixed a typo on -body (need to use XML output...)

**Comment by CernSteve** [comment]
Thanks for the update! We are in the process of testing here in a week or two. I'll let you know what we run into.

**Comment by justinmossb** [comment]
Sorry for the delay in our response, However the script worked really well. I used this code in a larger script that loaded a csv file with the old names and new names and was able to do a mass rename without issues.

**Comment by alagoutte** [comment]
@justinmossb Thanks for feedback

the next release with be include a Set-NsxLogicalSwitch (See #587)
