### ISSUE TITLE
Disable SSH on NSX Edge and SSH Manager

### ISSUE THREAD

**Issue by michaelshaoul** [vmware/powernsx#588]
need powercli or powernsx method to disable SSH in NSX Manager appliance and NSX Edge
stop-Service -Name ssh-agent , didn't give an error but didn't stop services either

**Comment by alagoutte** [comment]
There is no yet PowerNSX for disable SSH for NSX Manager (may be need to look via CLI option)

for NSX-Edge, you can use 

```powershell
Get-NsxEdge Edge01 | Disable-NsxEdgeSsh`

**Comment by michaelshaoul** [comment]
works

**Comment by alagoutte** [comment]
For Manager, there is no yet dedicated cmdlet, but you can use


```powershell
PS > (Invoke-NsxRestMethod -uri "/api/1.0/appliance-management/components/component/ssh"-method "get").component


componentId         : SSH
name                : SSH Service
description         : Secure Shell
status              : RUNNING
enabled             : true
showTechSupportLogs : false
usedBy              :
componentGroup      : SYSTEM



PS > (Invoke-NsxRestMethod -uri "/api/1.0/appliance-management/components/component/ssh/toggleStatus/stop" -method "post").result

result operationStatus
------ ---------------
result SUCCESS


PS > (Invoke-NsxRestMethod -uri "/api/1.0/appliance-management/components/component/ssh"-method "get").component


componentId         : SSH
name                : SSH Service
description         : Secure Shell
status              : STOPPED
enabled             : true
showTechSupportLogs : false
usedBy              :
componentGroup      : SYSTEM
```

use 
```powershell
 PS > (Invoke-NsxRestMethod -uri "/api/1.0/appliance-management/components/component/ssh/toggleStatus/start" -method "post").result
```

for start the composent/service

**Comment by michaelshaoul** [comment]
Do you know if there is a Invoke-NsxRestMethod for the Edge as well as the appliance ?

**Comment by alagoutte** [comment]
There is already Enable-NsxEdgeSsh  / Disabled-NsxEdgeSsh 

but if you really need the URI, it is : 

```powershell
$URI = "/api/4.0/edges/$($Edge.Edgesummary.ObjectId)/cliremoteaccess?enable=false"
```

$Edge.Edgesummary.ObjectId is Edge ObjectId (can be found via (Get-nsxEdge Edge01).edgeSummary )

**Comment by michaelshaoul** [comment]
Hello Alexis,

Sorry to bother, however the repository "vCheckReport/vCheck-NSX" has a pluggin 155 for backup check. It is missing a function or something. Do you know how I would find it ?

thanks

Mike
________________________________

**Comment by michaelshaoul** [comment]
thanks for your help with ssh, new issue opened for vchecknsx pluggin issue
