### ISSUE TITLE
show control-cluster network ipsec status error

### ISSUE THREAD

**Issue by michaelshaoul** [vmware/powernsx#591]
PS C:\WINDOWS\system32> show control-cluster network ipsec status
show : The term 'show' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ show control-cluster network ipsec status
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (show:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I'm very new to PowerNSX, but please tell why do I get the above error ? and is there a fix ?

**Comment by alagoutte** [comment]
Hi,

_show control-cluster network ipsec status_ is not a PowerNSX cmdlet but it is a command for CLI (on NSX Controller)

You can look to use NSX Cli cmdlet (via Invoke-NsxCli)

**Comment by michaelshaoul** [comment]
thanks

**Comment by michaelshaoul** [comment]
Hello Alexis, do you know of a command to connect to the controller cluster , perhaps something similar to Connect-NSXServer that I use to connect to the NSX Manager ?

**Comment by alagoutte** [comment]
When you use Connect-NsxServer, you can query NSX Controller

What do you need ?

**Comment by michaelshaoul** [comment]
I ran  "Connect-NsxServer" command and entered credentials. Then I ran "show control-cluster network ipsec status" .

show : The term 'show' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1​
+ show control-cluster network ipsec status​
+ ~~~~​
    + CategoryInfo          : ObjectNotFound: (show:String) [], CommandNotFoundException​
    + FullyQualifiedErrorId : CommandNotFoundException

Since "show control-cluster network ipsec status is not a PowerNSX cmdlet but it is a command for CLI (on NSX Controller)"
So how do I connect to controller via Cli command ? so I may run "show control-cluster network ipsec status"

________________________________

**Comment by alagoutte** [comment]
Sorry it is not possible with API to get this info actually 

it is only possible to call CLI for a Edge

**Comment by michaelshaoul** [comment]
thanks Alexis
