### ISSUE TITLE
Is there a way to list all unpublished firewall rules?

### ISSUE THREAD

**Issue by haripetrov** [vmware/powernsx#605]
When we login to the vCenter server > Network & Security > Firewall >  Check under “Unpublished” section if there are unpublished firewall rules
but we cannot find details regarding which are these firewall rules (id, name, etc.).
Is there a way to list them using PowerNSX? I couldn't find anything specific under Get-NsxFirewallRule

**Comment by dcoghlan** [comment]
PowerNSX will only be able to show you rules that have been saved/published in the management plane.

Maybe try a private browser to see if that makes a difference? The web-client plugin might also be caching some stuff.

You may need to log a ticket with GSS if you cannot resolve it with the private browser.

**Comment by haripetrov** [comment]
The unpublished rules were pretty old so no caching.
I already opened a case with VMware but meanwhile I wanted to check if there is another option.
Thanks for your help!
