### ISSUE TITLE
DFW Change Notes

### ISSUE THREAD

**Issue by Sk83r** [vmware/powernsx#606]
Hi guys

Is there any way to change notes (comments) in DFW rules ?

$rule = get-nsxfirewallrule -ruleid xxx
$rule.notes = "my comment"

How should I publish it now ?

Is there any PS script for bulk use per range of IDs or Section ? would be very handy

Thanks

**Comment by alagoutte** [comment]
Hi @Sk83r 

if you using this :
```powershell
$rule | Set-NsxFirewallrule 
```
the notes is updated ?

if you $rule have multiple rule inside, you can use also | Set-nsxFirewallRule

**Comment by Sk83r** [comment]
yes updated. Great!

How can I put into $rule array multiple rule IDs inside ?

**Comment by alagoutte** [comment]
Yes, there is no yet "notes" parameter but it can be easy to add...

**Comment by alagoutte** [comment]
After a quick check, what relase of NSX-V do you are using ?
because there is no notes field but description from NSX-V API Guide

**Comment by Sk83r** [comment]
Ver. 6.4. 3

**Comment by Sk83r** [comment]
But also if you can describe how to push multiple rule ids inside $rule array and how should I point each time to different rule id when I use $rule.notes

**Comment by alagoutte** [comment]
you need to store on $rule variable multiple rule

if you try
```powershell
$rules = get-nsxfirewallrule -id XX
$rules += get-nsxfirewallrule -id YY
```

**Comment by Sk83r** [comment]
> ```powershell
> $rules = get-nsxfirewallrule -id
> ```

$rules = get-nsxfirewallrule -ruleid XX

$rules += get-nsxfirewallrule -ruleid YY
Method invocation failed because [System.Xml.XmlElement] does not contain a method named 'op_Addition'.
At line:1 char:1
+ $rules += get-nsxfirewallrule -ruleid YY
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

**Comment by Sk83r** [comment]
> 
> 
> yes updated. Great!
> 
> How can I put into $rule array multiple rule IDs inside ?
> 
> I've tried Set-NsxFirewallRule with single id and -notes not a parameter in that command
> `get-nsxfirewallrule -ruleid xxx| Set-NsxFirewallRule -notes "mycomment"`

any alternative to this one which not supported ?

**Comment by alagoutte** [comment]
Need to add -notes parameter to Set-NsxFirewallRule

I will look later

**Comment by Sk83r** [comment]
Hey Alexis

Really need it please 🙏
I also noticed I can't set notes using var ($rule fo instance) if ruleid never had note before.

Means it's only possible to update existing notes in rules but not to set new ones.

**Comment by alagoutte** [comment]
Need to modified Set-NsxFirewallRule, i will try to look this week end

**Comment by Sk83r** [comment]
Have you had the chance to look into it?

**Comment by alagoutte** [comment]
Yes, i need to finish test...

**Comment by alagoutte** [comment]
@Sk83r do you have try ? (it is available on last release of powernsx)

**Comment by Sk83r** [comment]
Yes. Works like a charm! Exactly what I needed.

Appriciate your assistance, Alexis
