### ISSUE TITLE
Add in the Wiki, a new TOOL section

### ISSUE THREAD

**Issue by ddesmidt** [vmware/powernsx#61]
The tools I'm aware are:
  . Visio
    The explanation page is under http://networkinferno.net/nsx-visio-diagramming-tool
  . Excel
    The explanation page is under https://github.com/tonysangha/PowerNSX-Scripts
  . The Edge copy
    The explanation page is under https://powernsx.github.io/nsx/powernsx/edge/operations/2016/11/03/Copy-Nsx-Edge.html

Would be cool if those were referenced under the Wiki / Tool page => knowledge is shared.

Dimitri

**Comment by pandom** [comment]
Hey Dimitri,

powernsx.github.io will be the primary site `wiki` going forward. In conjunction with this, I will make a tool page and reference people who make tools there.

This gives me control over 'wiki' due to permissions in the VMware Github .

-Anthony

**Comment by nmbradford** [comment]
@pandom completed
