### ISSUE TITLE
visualize nested SGs in DFW

### ISSUE THREAD

**Issue by Sk83r** [vmware/powernsx#619]
Hi guys

is there any way to visualize nested SG association using special command ?

When you create new SG and attach it to other bigger existing SG , hard to tell if this new SG being used in the DFW policy table, specially if you have 600+ SGs.

I want to find an easy way to get like a tree of SG association.

Thanks

**Comment by Sk83r** [comment]
anybody please ?

**Comment by alagoutte** [comment]
Hi @Sk83r, 

I check and no found this cmdlet actually, i think, you need to write a loop for this

**Comment by dcoghlan** [comment]
PowerNSX does not have this capability. This was something that we got working in our Magpie Appliance v0.3 (https://github.com/nmbradford/magpie-release/), but that project is now stalled.

**Comment by dcoghlan** [comment]
@Sk83r  vRealise Network Insight is able to provide you with Security Group visualisations if you have it.
