### ISSUE TITLE
Support Security Group/Policy manipulation

### ISSUE THREAD

**Issue by dillson** [vmware/powernsx#63]
Support manipulation of NSX Service Composer objects.

- Creation of a new security policy
- Modification of an existing security policy
- Attachment of a security policy to a security group
- Support / document security group associations based on object types beyond tags

**Comment by nmbradford** [comment]
Already significant work by community on this though will require some review work.  Pushing to 2.2 as not critical feature request

**Comment by nmbradford** [comment]
Completed as of #447
