### ISSUE TITLE
An unknown exception occured calling invoke-internalwebrequest

### ISSUE THREAD

**Issue by cpitchai** [vmware/powernsx#632]
Getting the below error while trying to create a switch.

WebRequest: /root/.local/share/powershell/Modules/PowerNSX/3.0.1174/PowerNSX.psm1:10095
 Line |
10095 |  … $response = invoke-nsxwebrequest -method "post" -uri $URI -body $body …
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | Invoke-NsxWebRequest : An unknown exception occured calling invoke-internalwebrequest. System.Management.Automation.PSArgumentException: Cannot find type [InternalHttpClientHandler]:
      | verify that the assembly containing this type is loaded.    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord) in
      | /usr/src/photon/BUILD/PowerShell-7.0.0/src/System.Management.Automation/engine/MshCommandRuntime.cs:line 2078  StackTrace: at Invoke-InternalWebRequest,
      | /root/.local/share/powershell/Modules/PowerNSX/3.0.1174/PowerNSX.psm1: line 3825 at Invoke-NsxWebRequest, /root/.local/share/powershell/Modules/PowerNSX/3.0.1174/PowerNSX.psm1: line
      | 4324 at New-NsxLogicalSwitch<Process>, /root/.local/share/powershell/Modules/PowerNSX/3.0.1174/PowerNSX.psm1: line 10095 at Get-NsxTransportZone,
      | /root/.local/share/powershell/Modules/PowerNSX/3.0.1174/PowerNSX.psm1: line 9232 at <ScriptBlock>, <No file>: line 1
PropertyNotFoundException: /root/.local/share/powershell/Modules/PowerNSX/3.0.1174/PowerNSX.psm1:10098
 Line |
10098 |          Get-NsxLogicalSwitch -virtualWireId $response.content -connec …
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | The property 'content' cannot be found on this object. Verify that the property exists.

**Comment by alagoutte** [comment]
Hi,

What cmdlet do you are using ?

What release of NSX-V ?

**Comment by cpitchai** [comment]
New-NsxLogicalSwitch -Name Test -TransportZone $transportzone
Version             : 6.4.6
BuildNumber         : 14819921
Credential          : System.Management.Automation.PSCredential
Server              : X.X.X
Port                : 443
Protocol            : https

**Comment by cpitchai** [comment]
vCenter version
6.7
VMware NSX networking solution
NSX-V
NSX for vSphere
6.4.6-14819921

**Comment by cpitchai** [comment]
I am able to run the same command from using this docker image.  "docker.io/vmware/powerclicore:ubuntu16.04

**Comment by alagoutte** [comment]
What release of PowerNSX ?

What do you have on $transportzone variable ?

What the platform ?

**Comment by cpitchai** [comment]
PowerNSX  Version 3.0.1174
$transportzone = Get-NsxTransportZone "name of the transportzone"
Its a VMWARE on Softlayer

**Comment by cpitchai** [comment]
I am using this docker image "docker pull vmware/powerclicore"

**Comment by alagoutte** [comment]
may be need to update powerclicore (powershell release), look a internal error with the docker image...

**Comment by cpitchai** [comment]
Thank you.

**Comment by dcoghlan** [comment]
Closing issue.
