### ISSUE TITLE
Disable or turn off feature with PowerNSX

### ISSUE THREAD

**Issue by dwchan69** [vmware/powernsx#636]
I am able to automate most of what I want to a DLR with PowerNSX.  However, I can't seem to find the coomandlet or switch to disable the following

I can enable BGP GracefulRestart (which I think is by default) with
$dlr2 = Get-NsxLogicalRouter -Name Test-DLR2
$dlr2 | Get-NsxLogicalRouterRouting | Set-NsxLogicalRouterRouting -EnableBgpRouteRedistribution -confirm:$false

But I can't seem to find a way to disable BGP GracefulRestart?

I can enable Route Redistribution Status for BGP with
$dlr2 = Get-NsxLogicalRouter -Name Test-DLR2
$dlr2 | Get-NsxLogicalRouterRouting | Set-NsxLogicalRouterRouting -EnableBgpRouteRedistribution -confirm:$false

But I can't seem to find a way to disable it for OSPF

Now, this is not required but would be nice.  I can add new entries to Route Redistribution Table with
$dlr2 = Get-NsxLogicalRouter -Name Test-DLR2
$dlr2 | Get-NsxLogicalRouterRouting | New-NsxLogicalRouterRedistributionRule -FromConnected -Learner bgp -confirm:$false

But I can't seem to find a way to remove exist OSPF entries

Not sure if this is the limitation to PowerNSX, so any comment or feedback would be appreciated

**Comment by alagoutte** [comment]
Hi @dwchan69 


> I am able to automate most of what I want to a DLR with PowerNSX. However, I can't seem to find the coomandlet or switch to disable the following
> 
> I can enable BGP GracefulRestart (which I think is by default) with
> $dlr2 = Get-NsxLogicalRouter -Name Test-DLR2
> $dlr2 | Get-NsxLogicalRouterRouting | Set-NsxLogicalRouterRouting -EnableBgpRouteRedistribution -confirm:$false
> 
There is a typo 
You can to say : 
```powershell 
$dlr2 | Get-NsxLogicalRouterRouting | Set-NsxEdgeBGP -GracefulRestart -confirm:$false
```
> But I can't seem to find a way to disable BGP GracefulRestart?

use -Gracefulrestart:$false
> 
> I can enable Route Redistribution Status for BGP with
> $dlr2 = Get-NsxLogicalRouter -Name Test-DLR2
> $dlr2 | Get-NsxLogicalRouterRouting | Set-NsxLogicalRouterRouting -EnableBgpRouteRedistribution -confirm:$false
> 
> But I can't seem to find a way to disable it for OSPF
> 
use 
```powershell
$dlr2 | Get-NsxLogicalRouterRouting | Set-NsxLogicalRouterRouting -EnableOspfRouteRedistribution:$false -Confirm:$false
```

> Now, this is not required but would be nice. I can add new entries to Route Redistribution Table with
> $dlr2 = Get-NsxLogicalRouter -Name Test-DLR2
> $dlr2 | Get-NsxLogicalRouterRouting | New-NsxLogicalRouterRedistributionRule -FromConnected -Learner bgp -confirm:$false
> 
> But I can't seem to find a way to remove exist OSPF entries
You can use
```powershell
Get-NsxLogicalRouter LogicalRouter01 | Get-NsxLo
gicalRouterRouting | Get-NsxLogicalRouterRedistributionRule -Learner ospf | Remove-NsxLogicalRouterRedistributionRule
```
i will be remove all OSPF Redistribution Rule
> 
> Not sure if this is the limitation to PowerNSX, so any comment or feedback would be appreciated

**Comment by dwchan69** [comment]
Awesome, I was declaring the boolean as just $false without the colon and getting XML format error.  Will give this a try.  Thank you so much again for the speedy response

**Comment by dwchan69** [comment]
Update, I was able to disable gracefulRestart on the DLR with this

$dlr2 | Get-NsxLogicalRouterRouting | Set-NsxLogicalRouterBgp -GracefulRestart:$false -confirm:$false 

And it turns out that once I disable OSPF Router Redistribution as pointed out by you, the existing OSPF rule got auto deleted ;)

$dlr2 | Get-NsxLogicalRouterRouting | Set-NsxLogicalRouterRouting -EnableOspfRouteRedistribution:$false -Confirm:$false

Thank you again for the helps

**Comment by alagoutte** [comment]
You're welcome :)
