### ISSUE TITLE
Enable SSH and set management IP on DLR

### ISSUE THREAD

**Issue by dwchan69** [vmware/powernsx#637]
Just curious, can PowerNSX enable SSH on a DLR during or after deployment?  Also, can it set the management IP by chance also?  No critical, more curious than anything else

**Comment by alagoutte** [comment]
Hi @dwchan69 

Do you have look to use **_Enable-SSH_** ?
for management IP, i think, it is possible when your deploy the DLR

**Comment by dwchan69** [comment]
That's the thing, based on context sensitive info and the PowerNSX pdf, I don't explicitly see SSH or Management IP switch within the New-NSXLogicalRouter commandlet

**Comment by alagoutte** [comment]
for Enable-SSH is a cmdlet Get-NsxEdge myEdge | Enable-SSH (i don't known if work also for LogicalRouter/DLR

**Comment by dwchan69** [comment]
Was hoping there is an Enable-SSH switch for DLR also, but no big e

**Comment by alagoutte** [comment]
> 
> 
> Was hoping there is an Enable-SSH switch for DLR also, but no big e

it is not case sensible... ?!
