### ISSUE TITLE
Unable to connect to NSX Manager (2.5.x) with PowerCLI 12.2.0

### ISSUE THREAD

**Issue by robinher** [vmware/powernsx#644]
When using PowerCLI v12.2.0 to connect to vSphere management components, the connection to NXS Manager v2.5.x fails while connections to vCenter and HCX manager in the same network segment are succesfull.

Install-Module -Name VMware.PowerCLI
Import-Module VMware.PowerCLI
 
$AVSdomainsuffix = ".d33216387c3e4da5a03511.westus.avs.azure.com"
 
$VCUser = <VCAdmin username>
$NSXUser = <NSX Admin username>
$Password = "<INSERT_CORRECT_PASSWORD_HERE>"
 
Connect-VIServer -Server 10.250.160.2 -User $VCUser -Password $Password
Connect-HCXServer -Server 10.250.160.9 -User $VCUser -Password $Password
 
$NSXTServerName = "nsx$AVSdomainsuffix"
Connect-NsxtServer -Server $NSXTServerName -User $NSXUser -Password $Password
Connect-NsxtServer -Server 10.250.160.3 -User $NSXUser -Password $Password 

Results:
PS C:\Users\<deleted for security reasons>\Desktop\PowerCLI> Install-Module -Name VMware.PowerCLI
 
PS C:\Users\<deleted for security reasons>\Desktop\PowerCLI> Import-Module VMware.PowerCLI
WARNING: Please consider joining the VMware Customer Experience Improvement Program, so you can help us make PowerCLI a better product. You can join using the following command:
 
Set-PowerCLIConfiguration -Scope User -ParticipateInCEIP $true
 
VMware's Customer Experience Improvement Program ("CEIP") provides VMware with information that enables VMware to improve its products and services, to fix problems, and to advise you on how best to deploy and use our products.  A
s part of the CEIP, VMware collects technical information about your organizationâ€™s use of VMware products and services on a regular basis in association with your organizationâ€™s VMware license key(s).  This information does n
ot personally identify any individual.
 
For more details: type "help about_ceip" to see the related help article.
 
To disable this warning and set your preference use the following command and restart PowerShell: 
Set-PowerCLIConfiguration -Scope User -ParticipateInCEIP $true or $false.
          Welcome to VMware PowerCLI!
 
Log in to a vCenter Server or ESX host:              Connect-VIServer
To find out what commands are available, type:       Get-VICommand
To show searchable help for all PowerCLI commands:   Get-PowerCLIHelp
Once you've connected, display all virtual machines: Get-VM
If you need more help, visit the PowerCLI community: Get-PowerCLICommunity
 
       Copyright (C) VMware, Inc. All rights reserved.
 
 
 
PS C:\Users\<deleted for security reasons>\Desktop\PowerCLI> $AVSdomainsuffix = ".d33216387c3e4da5a03511.westus.avs.azure.com"
 
$VCUser = <deleted for security reasons>
$NSXUser = <deleted for security reasons>
$Password = <deleted for security reasons>
 
PS C:\Users\<deleted for security reasons>\Desktop\PowerCLI> Connect-VIServer -Server 10.250.160.2 -User $VCUser -Password $Password
 
Name                           Port  User                          
----                           ----  ----                          
10.250.160.2                   443   <deleted for security reasons>     
 
 
 
PS C:\Users\<deleted for security reasons>\Desktop\PowerCLI> Connect-HCXServer -Server 10.250.160.9 -User $VCUser -Password $Password
 
Server                         User                          
------                         ----                          
10.250.160.9                   <deleted for security reasons>      
 
 
 
PS C:\Users\<deleted for security reasons>\Desktop\PowerCLI> Connect-NsxtServer -Server 10.250.160.3 -User $NSXUser -Password $Password
Connect-NsxtServer : 2/24/2021 12:45:59 PM      Connect-NsxtServer        Unable to connect to the remote server     
At line:1 char:1
+ Connect-NsxtServer -Server 10.250.160.3 -User $NSXUser -Password $Pas ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-NsxtServer], CisException
    + FullyQualifiedErrorId : ConnectSingleServer_UnhandledException,VMware.VimAutomation.Cis.Nsxt.Commands.Cmdlets.ConnectNsxtServer

**Comment by alagoutte** [comment]
Hi Robin,

powernsx is only for NSX-V (for v-Sphere)

There is official module with "High API level" on PowerCLI (using Connect-nsxtserver and Get-NsxtService, you can look https://cloudmaniac.net/powercli-nsx-t-module/)
or there is a unofficial module [psNSXT ](https://github.com/psNSXT/psNSXT);-)

**Comment by dcoghlan** [comment]
Closing as issue is not related to NSX-v
