### ISSUE TITLE
New-NsxEdgeBgpNeighbour is not using password

### ISSUE THREAD

**Issue by sk8tony** [vmware/powernsx#76]
I found that the commandlet New-NsxEdgeBgpNeighbour is accepting -password parameter but never sets it to neighbor configuration.
In the PowerNSX.psm1 the function is defined on row: 13326

I modified it- after row 13427 added:
if ( $PsBoundParameters.ContainsKey("Password") ) { 
                Add-XmlElement -xmlRoot $Neighbour -xmlElementName "password" -xmlElementText $Password.ToString()
            }

Now the newly created BGP Neighbour is configured with provided password

**Comment by nmbradford** [comment]
Thanks @sk8tony, looks like the same omission is in New-NsxLogicalRouterBgpNeighbour.

**Comment by nmbradford** [comment]
pushing to 2.2 as non critical
