### ISSUE TITLE
PowerNSX Installer bootstrap does not work in PowerShell Core.

### ISSUE THREAD

**Issue by nmbradford** [vmware/powernsx#83]

**Comment by pandom** [comment]
Here is the text.

`new-object : Cannot find type [Net.WebClient]: verify that the assembly containing this type is loaded.
At line:1 char:118
+ ... /PowerNSXInstaller.ps1"; try { $wc = new-object Net.WebClient;$scr =  ...
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand`

**Comment by nmbradford** [comment]
updated bootstrap text  (PowerShell 3 and above specific.)

```
$pp = $ProgressPreference;$global:ProgressPreference = "silentlycontinue"; $Branch="master";$url="https://raw.githubusercontent.com/vmware/powernsx/$Branch/PowerNSXInstaller.ps1"; try { try { $response = Invoke-WebRequest -uri $url; $scr = $response.content } catch { if ( $_.exception.innerexception -match "(407)") { $credentials = Get-Credential -Message "Proxy Authentication Required"; $response = Invoke-WebRequest -uri $url -proxyCredential $credentials; $scr = $response.content } else { throw $_ }}; $scr | iex } catch { throw $_ };$global:ProgressPreference = $pp
```
