### ISSUE TITLE
[PowerNsx/PowerNSXCore] Get-NsxManagerSyslogServer does not work correctly when no syslog settings defined.

### ISSUE THREAD

**Issue by dcoghlan** [vmware/powernsx#87]
On a NSX Manager that doesn't have any syslog settings defined, running Get-NsxManagerSyslogServer on both Windows and MacOS produces the following error.

[PS /Users/dcoghlan> Get-NsxManagerSyslogServer                                                                                                                  
The property 'syslogServer' cannot be found on this object. Verify that the property exists.
At /Users/dcoghlan/.local/share/powershell/Modules/PowerNSX/PowerNSX.psm1:5161 char:9
+         Add-XmlElement -xmlRoot $xmlSyslog -xmlElementName "syslogSer ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
 
The property 'port' cannot be found on this object. Verify that the property exists.
At /Users/dcoghlan/.local/share/powershell/Modules/PowerNSX/PowerNSX.psm1:5162 char:9
+         Add-XmlElement -xmlRoot $xmlSyslog -xmlElementName "port" -xm ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
 
The property 'protocol' cannot be found on this object. Verify that the property exists.
At /Users/dcoghlan/.local/share/powershell/Modules/PowerNSX/PowerNSX.psm1:5163 char:9
+         Add-XmlElement -xmlRoot $xmlSyslog -xmlElementName "protocol" ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
 

Name            : syslogserver
LocalName       : syslogserver
NamespaceURI    : 
Prefix          : 
NodeType        : Element
ParentNode      : #document
OwnerDocument   : #document
IsEmpty         : True
Attributes      : {}
HasAttributes   : False
InnerXml        : 
InnerText       : 
NextSibling     : 
PreviousSibling : 
Value           : 
ChildNodes      : {}
FirstChild      : 
LastChild       : 
HasChildNodes   : False
IsReadOnly      : False
OuterXml        : <syslogserver />
BaseURI         : 
PreviousText    :

**Comment by nmbradford** [comment]
causing test failures - need fixed by 2.1

**Comment by nmbradford** [comment]
Oh - I was just about to fix that bug got distracted by another bug! :)  Thanks!
