### ISSUE TITLE
New-NsxSecurityTagAssignment function fails to submit proper parameters to Invoke-NsxWebRequest

### ISSUE THREAD

**Issue by msherian** [vmware/powernsx#93]
Hello PowerNSX Team,

I was attempting to utilise your great toolset, but ran into an issue with the NsxSecurityTagAssignment function:
`PowerCLI C:\> New-NsxSecurityTagAssignment -ApplyTag (Get-NsxSecurityTag XXXXX) -VirtualMachine (Get-VM XXXXX)`
`invoke-nsxwebrequest : Invoke-NsxWebRequest : Exception occured calling invoke-restmethod.`
`System.Management.Automation.RuntimeException: Cannot specify put request`
`without a body.`
`At C:\Users\XXXXXXXX\Documents\WindowsPowerShell\modules\PowerNSX\PowerNSX.psm1:19562 char:29`
`+ ... $response = invoke-nsxwebrequest -method "put" -uri $URI -connection  ...`
`+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : InvalidResult: (Invoke-NsxWebRequest:String) [Invoke-NsxWebRequest],`
`InternalNsxApiException`
`    + FullyQualifiedErrorId : NsxAPIFailureResult,Invoke-NsxWebRequest`

I found a work around, but this may not be the proper way to resolve the issue, but it did work for me.
`@@ -19562 +19677 @@`
`-                $response = invoke-nsxwebrequest -method "put" -uri $URI -connection $connection`
`+                $response = invoke-nsxwebrequest -method "put" -uri $URI -connection $connection -body ""`

**Comment by nmbradford** [comment]
Oops - that last commit reference was inadvertant - I most certainly havent fixed this (yet).  Sorry, and stand by...!

**Comment by nmbradford** [comment]
Yeah - Ive broken this with the changes to support PowerNSX on PowerShell Core :(  Nice catch - thanks!  Im testing a fix now.

**Comment by nmbradford** [comment]
ok - this should really be fixed now!  Thanks for the report @msherian!

**Comment by msherian** [comment]
No problem, glad to help!
